var latte;
(function(latte){var DataSetColumn=function(){function DataSetColumn(name,type,length){if(typeof name==="undefined")name="";if(typeof type==="undefined")type="";if(typeof length==="undefined")length=0;this.optionsChanged=new latte.LatteEvent(this);this.name=name;this.type=type;this.length=length}Object.defineProperty(DataSetColumn.prototype,"length",{get:function(){return this._length},set:function(value){this._length=value},enumerable:true,configurable:true});Object.defineProperty(DataSetColumn.prototype,"name",
{get:function(){return this._name},set:function(value){this._name=value},enumerable:true,configurable:true});DataSetColumn.prototype.onOptionsChanged=function(){this.optionsChanged.raise()};Object.defineProperty(DataSetColumn.prototype,"options",{get:function(){return this._options},set:function(value){this._options=value;this.onOptionsChanged()},enumerable:true,configurable:true});Object.defineProperty(DataSetColumn.prototype,"tag",{get:function(){return this._tag},set:function(value){this._tag=
value},enumerable:true,configurable:true});Object.defineProperty(DataSetColumn.prototype,"type",{get:function(){return this._type},set:function(value){this._type=value},enumerable:true,configurable:true});return DataSetColumn}();latte.DataSetColumn=DataSetColumn})(latte||(latte={}));var latte;
(function(latte){var DataSetRow=function(){function DataSetRow(data){if(typeof data==="undefined")data=[];this.data=data;if(data)this.data=data;else this.data=[]}DataSetRow.prototype.getDataArray=function(columns){var a=[];for(var i=0;i<columns;i++)if(latte._undef(this.data[i]))a[i]=null;else a[i]=this.data[i];return a};DataSetRow.prototype.hasValueAt=function(index){return!latte._undef(this.data[index])};Object.defineProperty(DataSetRow.prototype,"readOnly",{get:function(){return this._readOnly},
set:function(value){this._readOnly=value},enumerable:true,configurable:true});Object.defineProperty(DataSetRow.prototype,"tag",{get:function(){return this._tag},set:function(value){this._tag=value},enumerable:true,configurable:true});DataSetRow.prototype.getValueAt=function(index){return this.data[index]};DataSetRow.prototype.setValueAt=function(index,value){this.data[index]=value};return DataSetRow}();latte.DataSetRow=DataSetRow})(latte||(latte={}));
var __extends=this.__extends||function(d,b){for(var p in b)if(b.hasOwnProperty(p))d[p]=b[p];function __(){this.constructor=d}__.prototype=b.prototype;d.prototype=new __};var latte;
(function(latte){var GridView=function(_super){__extends(GridView,_super);function GridView(){var _this=this;_super.call(this);this._allowChangeRows=true;this._allowDeleteRows=true;this._allowNewRows=true;var gv=this;window["g"]=gv;this.element.addClass("grid");this.committed=new latte.LatteEvent(this);this.valueChanged=new latte.LatteEvent(this);this.rowsAdded=new latte.LatteEvent(this);this.rowsChanged=new latte.LatteEvent(this);this.rowsRemoved=new latte.LatteEvent(this);this.columns=new latte.Collection(this._onAddColumn,
this._onRemoveColumn,this);this.rows=new latte.Collection(this._onAddRow,this._onRemoveRow,this);this.table=$("<table>",{border:1}).appendTo(this.container).hide();this._trColumns=$("<tr>").addClass("headers").appendTo(this.table);this._tdAll=$("<th>").appendTo(this._trColumns);this.table.mouseleave(function(){_this._selectColumnHeader()});this.table.click(function(){_this.endCellEdit()});this.allowNewRows=this.allowNewRows;this._actionCommit=new latte.Action;this._actionCommit.text=strings.apply;
this._actionCommit.icon=latte.IconItem.standard(1,6);this._actionCommit.enabled=false;this._actionCommit.execute.add(function(){_this.commit()});this._actionRollback=new latte.Action;this._actionRollback.text=strings.revert;this._actionRollback.icon=latte.IconItem.standard(2,6);this._actionRollback.enabled=false;this._actionRollback.execute.add(function(){_this.rollback()});this._actionRemoveRow=new latte.Action;this._actionRemoveRow.text=strings.deleteRow;this._actionRemoveRow.icon=latte.IconItem.standard(11,
5);this._actionRemoveRow.execute.add(function(){_this.deleteRowAt(_this.selectedCell.data("rowIndex"))});this._actionCopyCellValue=new latte.Action;this._actionCopyCellValue.text=strings.copy;this._actionCopyCellValue.icon=latte.IconItem.standard(14,5);this._actionCopyCellValue.execute.add(function(){_this.copySelectedCellValue()});this._actionPasteCellValue=new latte.Action;this._actionPasteCellValue.text=strings.paste;this._actionPasteCellValue.icon=latte.IconItem.standard(15,4);this._actionPasteCellValue.execute.add(function(){});
this._actionSetCellNull=new latte.Action;this._actionSetCellNull.text=strings.setAsNull;this._actionSetCellNull.icon=latte.IconItem.empty(32);this._actionSetCellNull.execute.add(function(){_this.setValueAt(_this.selectedCell.data("columnIndex"),_this.selectedCell.data("rowIndex"),null,true)})}GridView.prototype._addInsertRow=function(){var row=this._createRow();var rowIndex=this.rows.count;row.removeClass("row").addClass("insert-row").appendTo(this.table).find("th").text("*");row.find("td").data("rowIndex",
rowIndex)};GridView.prototype._createCell=function(columnIndex,rowIndex){var gv=this;var cell=$("<td>").addClass("cell").data("rowIndex",rowIndex).data("columnIndex",columnIndex).click(function(){gv.selectCellAt($(this).data("columnIndex"),$(this).data("rowIndex"))}).dblclick(function(){if(!$(this).hasClass("editing"))gv.editCellAt($(this).data("columnIndex"),$(this).data("rowIndex"))}).mouseenter(function(){gv._selectColumnHeader($(this).data("columnIndex"));gv._selectRowHeader($(this).data("rowIndex"));
$(this).addClass("hover")}).mouseleave(function(){$(this).removeClass("hover")});latte.UiElement.disableTextSelection(cell);return cell};GridView.prototype._createRow=function(){var rowIndex=this.rows.count-1;var tr=$("<tr>").addClass("row").appendTo(this.table);tr.data("rowIndex",rowIndex);$("<th>").text(rowIndex+1+"").appendTo(tr);for(var i=0;i<this.columns.count;i++)this._createCell(i,rowIndex).appendTo(tr);return tr};GridView.prototype._makeInsertRowCandidate=function(){var row=new latte.GridViewRow;
this.rows.add(row,false);var count=this.rows.count;this.table.find("tr.insert-row").data("rowIndex",count-1);this.table.find("tr.insert-row th").text(count+"*");row.element=this.table.find("tr.insert-row").removeClass("insert-row").addClass("insertable-row");this._transactionStart()};GridView.prototype._onAddColumn=function(column){var _this=this;var th=$("<th>").appendTo(this._trColumns);var index=this.columns.count-1;column.header=th;column.optionsChanged.add(function(){for(var i=0;i<_this.rows.count;i++)_this.setValueAt(index,
i,_this.getValueAt(index,i),false)});th.text(column.name);this.table.show()};GridView.prototype._onAddRow=function(row){var rowIndex=this.rows.count-1;if(this._allowNewRows)this._removeInsertRow();this._createRow().appendTo(this.table);for(var i=0;i<this.columns.count;i++)if(this.hasValueAt(i,rowIndex)){var v=this.getValueAt(i,rowIndex);this.setValueAt(i,rowIndex,v)}row.element=this.getRowElementAt(rowIndex);if(this._allowNewRows)this._addInsertRow()};GridView.prototype._onRemoveColumn=function(column){column.header.remove();
this.allowNewRows=this.allowNewRows};GridView.prototype._onRemoveRow=function(row,index){row.element.remove();this._updateRowIndexes()};GridView.prototype._removeInsertRow=function(){this.table.find("tr.insert-row").remove()};GridView.prototype._selectColumnHeader=function(index){if(typeof index==="undefined")index=-1;this.table.find("th").removeClass("selected");if(index<0)this.columns.item(index).header.addClass("selected")};GridView.prototype._selectRowHeader=function(index){this.table.find("tr:eq("+
(index+1)+") > th").addClass("selected")};GridView.prototype._transactionEnd=function(){this.container.find(".insert-button").remove();this._actionCommit.enabled=false;this._actionRollback.enabled=false};GridView.prototype._transactionStart=function(){if(this.container.find(".insert-button").length)return;var bg=new latte.ButtonGroupItem;bg.buttons.add(this._actionCommit.getButton());bg.buttons.add(this._actionRollback.getButton());bg.element.addClass("insert-button").css({position:"absolute",right:5,
top:5,borderRadius:4,boxShadow:"0 0 5px rgba(0, 0, 0, 0.5)"}).appendTo(this.container);this._actionCommit.enabled=true;this._actionRollback.enabled=true};GridView.prototype._updateRowIndexes=function(){var i=0;this.table.find("tr:not(.headers)").each(function(){var tr=$(this);tr.data("rowIndex",i);tr.children().data("rowIndex",i);i++})};GridView.prototype.canEditCellAt=function(columnIndex,rowIndex){var row=this.getRowElementAt(rowIndex);var cell=this.hasCellAt(columnIndex,rowIndex)?this.getCellElementAt(columnIndex,
rowIndex):null;var canEdit=cell instanceof jQuery&&!this.readOnly&&!this.columns.item(columnIndex).readOnly&&!row.hasClass("pendent")&&!row.hasClass("deletable-row")&&this.allowChangeRows;if(this.rows.item(rowIndex))canEdit=canEdit&&!this.rows.item(rowIndex).readOnly;return canEdit};GridView.prototype.clearSelection=function(){this.table.find("td.selected").removeClass("selected")};GridView.prototype.commit=function(){this.commitAddedRows();this.commitChangedRows();this.commitDeletedRows();this._transactionEnd();
this.onCommitted()};GridView.prototype.commitAddedRows=function(){var d=new latte.DataSet;var indexes=[];this.endCellEdit();for(var i=0;i<this.columns.count;i++)d.columns.add(this.columns.item(i));this.table.find("tr.insertable-row").each(function(){var tr=$(this);tr.find("th").text(tr.data("rowIndex")+1);indexes.push(tr.data("rowIndex"));tr.removeClass("insertable-row").addClass("pendent pendent-insert")});for(var i=0;i<indexes.length;i++)d.rows.add(this.rows.item(indexes[i]));this.onRowsAdded(d)};
GridView.prototype.commitChangedRows=function(){var d=new latte.DataSet;var old=new latte.DataSet;var indexes=[];this.endCellEdit();d.columns.addCollection(this.columns);old.columns.addCollection(this.columns);this.table.find("tr.changeable-row").each(function(){var tr=$(this);indexes.push(tr.data("rowIndex"));tr.removeClass("changeable-row").addClass("pendent pendent-update")});for(var i=0;i<indexes.length;i++){var rowIndex=indexes[i];d.rows.add(this.rows.item(rowIndex));var row=new latte.DataSetRow;
old.rows.add(row);for(var j=0;j<old.columns.count;j++){var columnIndex=j;var value=this.originalValue(columnIndex,rowIndex);if(latte._undef(value))if(this.hasValueAt(columnIndex,rowIndex))value=this.getValueAt(columnIndex,rowIndex);else null;row.setValueAt(columnIndex,value)}}this.onRowsChanged(d,old)};GridView.prototype.commitDeletedRows=function(){var d=new latte.DataSet;var indexes=[];this.endCellEdit();d.columns.addCollection(this.columns);this.table.find("tr.deletable-row").each(function(){var tr=
$(this);tr.find("th").text(tr.data("rowIndex")+1);indexes.push(tr.data("rowIndex"));tr.removeClass("deletable-row").addClass("pendent pendent-delete")});for(var i=0;i<indexes.length;i++)d.rows.add(this.rows.item(indexes[i]));this.onRowsRemoved(d)};GridView.prototype.confirmRowsAdded=function(){this.table.find("tr.pendent-insert").removeClass("pendent pendent-insert")};GridView.prototype.confirmRowsChanged=function(){this.table.find("tr.pendent-update").removeClass("pendent pendent-update")};GridView.prototype.confirmRowsRemoved=
function(){var indexes=[];this.table.find("tr.pendent-delete").each(function(){indexes.push($(this).data("rowIndex"))});for(var i=indexes.length-1;i>=0;i--)this.rows.removeAt(indexes[i])};GridView.prototype.copySelectedCellValue=function(){var txtView=new latte.TextView;txtView.text=this.selectedCell.text();var btnOk=new latte.ButtonItem;btnOk.text=strings.ok;var d=new latte.DialogView(txtView,[btnOk]);d.show();txtView.textElement.focus();txtView.textElement.select()};GridView.prototype.deleteRowAt=
function(rowIndex){this.getRowElementAt(rowIndex).addClass("deletable-row");this._transactionStart()};GridView.prototype.editCellAt=function(columnIndex,rowIndex){if(!this.canEditCellAt(columnIndex,rowIndex))return;var gv=this;var td=this.getCellElementAt(columnIndex,rowIndex);var val=this.hasValueAt(columnIndex,rowIndex)?this.getValueAt(columnIndex,rowIndex):"";var col=this.columns.item(columnIndex);this.clearSelection();td.addClass("editing");var input=new latte.InputItem;input.type=col.type;input.options=
col.options;input.value=val;input.textVisible=false;input.element.find("input[type=text], input[type=password], textarea").width(td.width());td.empty().append(input.element).data("input",input);var elem=input.element.find("input, select, textarea");elem.keydown(function(evt){if(evt.keyCode==27)gv.endCellEdit(true);else if(evt.keyCode==9)if(evt.shiftKey)gv.editPreviousCell();else gv.editNextCell();else if(evt.keyCode==13)gv.endCellEdit(false)}).click(function(ev){ev.stopPropagation()});setTimeout(function(){elem.first().focus().select()},
100);this.endCellEdit();this._editingTd=td};GridView.prototype.editNextCell=function(){if(!this.editing)return;var rowCount=this.table.find("tr.row").length-1;var colCount=this.columns.count;var row=this._editingTd.data("rowIndex");var col=this._editingTd.data("columnIndex");if(col==colCount-1&&row==rowCount-1)return;if(col==colCount-1){col=0;row++}else col++;this.editCellAt(col,row)};GridView.prototype.editPreviousCell=function(){if(!this.editing)return;var colCount=this.columns.count;var row=this._editingTd.data("rowIndex");
var col=this._editingTd.data("columnIndex");if(row==0&&col==0)return;if(col==0){col=colCount-1;row--}else col--;this.editCellAt(col,row)};GridView.prototype.endCellEdit=function(cancelled){if(typeof cancelled==="undefined")cancelled=false;if(!this._editingTd||this._editingTd.length==0)return;var input=this._editingTd.data("input");var value=input.value;var row=this._editingTd.data("rowIndex");var col=this._editingTd.data("columnIndex");if(this._editingTd.parent().hasClass("insert-row")){if(cancelled!==
true){this._makeInsertRowCandidate();this._addInsertRow()}this.setValueAt(col,row,value)}else if(this._editingTd.parent().hasClass("insertable-row"))this.setValueAt(col,row,value);else if(cancelled!==true)this.setValueAt(col,row,value,true);else if(this.hasValueAt(col,row))this.setValueAt(col,row,this.getValueAt(col,row));if(!cancelled)this._editingTd.addClass("changeable-row");this._editingTd.data("input",null);this._editingTd.removeClass("editing");this._editingTd=null};GridView.prototype.getCellElementAt=
function(columnIndex,rowIndex){return this.table.find(latte.sprintf("tr:eq(%s) td:eq(%s)",rowIndex+1,columnIndex))};GridView.prototype.getData=function(){var d=new latte.DataSet;d.columns.addCollection(this.columns);d.rows.addCollection(this.rows);return d};GridView.prototype.getRowElementAt=function(rowIndex){return this.table.find(latte.sprintf("tr:eq(%s)",rowIndex+1))};GridView.prototype.getValueAt=function(columnIndex,rowIndex){if(this.hasValueAt(columnIndex,rowIndex))return this.rows.item(rowIndex).getValueAt(columnIndex);
else if(this.rows.count<=rowIndex)throw new latte.InvalidArgumentEx("rowIndex",rowIndex);else throw new latte.InvalidArgumentEx("columnIndex",columnIndex);};GridView.prototype.hasCellAt=function(columnIndex,rowIndex){return this.getCellElementAt(columnIndex,rowIndex).length>0};GridView.prototype.hasValueAt=function(columnIndex,rowIndex){return this.rows.count>rowIndex&&this.rows.item(rowIndex).hasValueAt(columnIndex)};GridView.prototype.onCommitted=function(){this.committed.raise()};GridView.prototype.onContextItemsShow=
function(){_super.prototype.onContextItemsShow.call(this);var hover=this.table.find("td.cell.hover");var columnIndex=hover.data("columnIndex");var rowIndex=hover.data("rowIndex");this.contextItems.clear();if(hover.length==0)return;this.selectCellAt(columnIndex,rowIndex);this._actionRemoveRow.enabled=!hover.parent().hasClass("insert-row")&&this.allowDeleteRows;this._actionSetCellNull.enabled=this.canEditCellAt(columnIndex,rowIndex);this.contextItems.add(this._actionCopyCellValue.getButton());this.contextItems.add(this._actionPasteCellValue.getButton());
this.contextItems.add(new latte.SeparatorItem);this.contextItems.add(this._actionSetCellNull.getButton());this.contextItems.add(this._actionRemoveRow.getButton())};GridView.prototype.onRowsAdded=function(dataset){this.rowsAdded.raise(dataset)};GridView.prototype.onRowsChanged=function(dataset,oldDataset){if(typeof oldDataset==="undefined")oldDataset=null;this.rowsChanged.raise(dataset,oldDataset)};GridView.prototype.onRowsRemoved=function(dataset){this.rowsRemoved.raise(dataset)};GridView.prototype.onValueChanged=
function(columnIndex,rowIndex,value,oldValue){this._transactionStart();this.getRowElementAt(rowIndex).addClass("changeable-row");if(latte._undef(this.originalValue(columnIndex,rowIndex)))this.originalValue(columnIndex,rowIndex,oldValue);this.valueChanged.raise({row:rowIndex,column:columnIndex,value:value,oldValue:oldValue})};GridView.prototype.originalValue=function(columnIndex,rowIndex,value){if(typeof value==="undefined")value=null;var cell=this.getCellElementAt(columnIndex,rowIndex);if(latte._undef(value))return cell.data("original-value");
cell.data("original-value",value);return this};GridView.prototype.restoreValueAt=function(columnIndex,rowIndex){if(!this.hasCellAt(columnIndex,rowIndex))return;var cell=this.getCellElementAt(columnIndex,rowIndex);if(!latte._undef(cell.data("original-value"))){this.setValueAt(columnIndex,rowIndex,cell.data("original-value"));cell.removeData("original-value")}};GridView.prototype.rollback=function(){var gv=this;this.endCellEdit();var indexes=[];this.table.find("tr.insertable-row").each(function(){indexes.push($(this).data("rowIndex"))});
for(var i=indexes.length-1;i>=0;i--)this.rows.removeAt(indexes[i]);this._removeInsertRow();if(this.allowNewRows)this.allowNewRows=this.allowNewRows;this.table.find("tr.deletable-row").removeClass("deletable-row");this.table.find("tr.changeable-row").each(function(){var rowIndex=$(this).data("rowIndex");for(var columnIndex=0;columnIndex<gv.columns.count;columnIndex++)gv.restoreValueAt(columnIndex,rowIndex)}).removeClass("changeable-row");this._transactionEnd()};GridView.prototype.selectCellAt=function(columnIndex,
rowIndex){this.clearSelection();this.getCellElementAt(columnIndex,rowIndex).addClass("selected")};GridView.prototype.setData=function(value){this.columns.clear();this.rows.clear();var row,col,buff=this.allowNewRows;while(col=value.columns.next())this.columns.add(new latte.GridViewColumn(col.name,col.type,col.length));this.allowNewRows=false;while(row=value.rows.next())this.rows.add(new latte.GridViewRow(row.data));this.allowNewRows=buff};GridView.prototype.setValueAt=function(columnIndex,rowIndex,
value,raiseEvent){if(typeof raiseEvent==="undefined")raiseEvent=false;var td=this.getCellElementAt(columnIndex,rowIndex);var oldValue=this.hasValueAt(columnIndex,rowIndex)?this.getValueAt(columnIndex,rowIndex):null;if(this.rows.count>rowIndex)this.rows.item(rowIndex).setValueAt(columnIndex,value);if(value===null)td.empty().append($("<div>").addClass("null").text("NULL"));else if(this.columns.item(columnIndex).type=="password"||this.columns.item(columnIndex).type=="md5-password")td.empty().html(latte.sprintf("(%s)",
strings.secret));else td.empty().html(latte.InputItem.format(value,this.columns.item(columnIndex).type,this.columns.item(columnIndex).options));if(raiseEvent===true)this.onValueChanged(columnIndex,rowIndex,value,oldValue)};Object.defineProperty(GridView.prototype,"allowChangeRows",{get:function(){return this._allowChangeRows},set:function(value){this._allowChangeRows=value},enumerable:true,configurable:true});Object.defineProperty(GridView.prototype,"allowDeleteRows",{get:function(){return this._allowDeleteRows},
set:function(value){this.allowDeleteRows=value},enumerable:true,configurable:true});Object.defineProperty(GridView.prototype,"allowNewRows",{get:function(){return this._allowNewRows},set:function(value){this._allowNewRows=value;if(value){this._removeInsertRow();if(!this.readOnly)this._addInsertRow()}else this._removeInsertRow()},enumerable:true,configurable:true});Object.defineProperty(GridView.prototype,"data",{get:function(){return this.getData()},set:function(value){this.setData(value)},enumerable:true,
configurable:true});Object.defineProperty(GridView.prototype,"editing",{get:function(){return this._editingTd?true:false},enumerable:true,configurable:true});Object.defineProperty(GridView.prototype,"readOnly",{get:function(){return this._readOnly},set:function(value){this._readOnly=value;if(value)this._removeInsertRow();else this.allowNewRows=this.allowNewRows},enumerable:true,configurable:true});Object.defineProperty(GridView.prototype,"selectedCell",{get:function(){return this.table.find("td.cell.selected")},
set:function(value){if(!(value instanceof jQuery))throw new latte.InvalidArgumentEx("value");this.selectCellAt(value.data("columnIndex"),value.data("rowIndex"))},enumerable:true,configurable:true});return GridView}(latte.View);latte.GridView=GridView})(latte||(latte={}));var latte;
(function(latte){var Cache=function(){function Cache(){}Cache.prototype.load=function(recordType,name,callback){if(typeof callback==="undefined")callback=null;return null};return Cache}();latte.Cache=Cache})(latte||(latte={}));var latte;
(function(latte){var DataRecord=function(){function DataRecord(){this.tags={};var metadata=this.getMetadata();if(metadata&&latte._isObject(metadata.fields))for(var i in metadata.fields)this[i]=""}DataRecord.scanAndConvert=function(obj){if(obj&&latte._isObject(obj)||latte._isArray(obj))if(latte.DataRecord.isPackedRecord(obj))obj=latte.DataRecord.fromServerObject(obj);else for(var i in obj)obj[i]=latte.DataRecord.scanAndConvert(obj[i]);return obj};DataRecord.setDefaultRecordsNamespace=function(namespace){latte.DataRecord._defaultRecordsNamespace=
namespace;for(var symbol in namespace){namespace[symbol].recordType=symbol;namespace[symbol].fromServerObject=latte.DataRecord.fromServerObject;namespace[symbol].fromServerObjects=latte.DataRecord.fromServerObjects}};DataRecord.fromName=function(name,id,callback){var m=(new latte.Message("_core","DataLatteUa","recordSelect",{name:name,id:id})).send(function(record){callback(record)});return m};DataRecord.fromServerObject=function(obj,classType){if(typeof classType==="undefined")classType=null;var dns=
latte.DataRecord._defaultRecordsNamespace?latte.DataRecord._defaultRecordsNamespace:latte._isObject(window[DataRecord.recordsNamespaceName])?window[DataRecord.recordsNamespaceName]:null;var rt=obj.recordType;var type=latte._isFunction(classType)?classType:latte._isFunction(dns[rt])?dns[rt]:DataRecord;var record=new type;var i,j;if(!latte.DataRecord.isPackedRecord(obj))throw new latte.Ex;for(i in obj.fields)record[i]=obj.fields[i];record.recordType=obj.recordType;record.recordId=obj.recordId;if(obj.metadata)record.metadata=
obj.metadata||{};if(!latte._undef(obj["properties"]))for(i in obj.properties){if(latte._isArray(obj.properties[i]))for(j=0;j<obj.properties[i].length;j++)obj.properties[i][j]=latte.DataRecord.fromServerObject(obj.properties[i][j]);if(obj.properties[i]&&obj.properties[i]["type"]=="DataRecord")record[i]=latte.DataRecord.fromServerObject(obj.properties[i]);else record[i]=obj.properties[i]}return record};DataRecord.fromServerObjects=function(array,classType){if(typeof classType==="undefined")classType=
null;if(!latte._isArray(array))throw new latte.InvalidArgumentEx("array",array);var a=[];for(var i=0;i<array.length;i++)a.push(latte.DataRecord.fromServerObject(array[i],classType));return a};DataRecord.isPackedRecord=function(object){return latte._isObject(object)&&object.type=="DataRecord"&&!latte._undef(object.recordType)};DataRecord.prototype.createView=function(){return new latte.DataRecordFormView(this)};DataRecord.prototype.getFields=function(){var f={};var metadata=this.getMetadata();if(metadata&&
metadata.fields)for(var i in metadata.fields)f[i]=this[i]||null;return f};DataRecord.prototype.getMetadata=function(){return this.metadata};DataRecord.prototype.insert=function(callback){return this.insertCall().send(function(){if(latte._isFunction(callback))callback()})};DataRecord.prototype.insertCall=function(){var _this=this;var values=this.getFields();for(var i in values)if(values[i]===null)values[i]="";var call=new latte.RemoteCall(this.moduleName,"DataLatteUa","recordInsert",{name:this.recordType,
fields:values});call.success.add(function(data){_this.recordId=parseInt(data,10);_this[_this.onGetRecordIdName()]=_this.recordId});return call};DataRecord.prototype.inserted=function(){return this.recordId>0};DataRecord.prototype.onFormCreated=function(form){if(this._formCreated)this._formCreated.raise(form)};DataRecord.prototype.onFormCreating=function(form){if(this._formCreating)this._formCreating.raise(form)};DataRecord.prototype.onGetRecordIdName=function(){return undefined};DataRecord.prototype.onViewCreated=
function(view){if(this._viewCreated)this._viewCreated.raise(view)};DataRecord.prototype.onViewCreating=function(view){if(this._viewCreating)this._viewCreating.raise(view)};DataRecord.prototype.remove=function(callback){return this.removeCall().send(function(){if(latte._isFunction(callback))callback()})};DataRecord.prototype.removeCall=function(){return new latte.RemoteCall(this.moduleName,"DataLatteUa","recordDelete",{name:this.recordType,id:this.recordId})};DataRecord.prototype.save=function(callback){return this.saveCall().send(function(){if(latte._isFunction(callback))callback()})};
DataRecord.prototype.saveCall=function(){if(this.recordId)return this.updateCall();else return this.insertCall()};DataRecord.prototype.update=function(callback){return this.updateCall().send(function(){if(latte._isFunction(callback))callback()})};DataRecord.prototype.updateCall=function(){var values=this.getFields();for(var i in values)if(values[i]===null)values[i]="";var call=new latte.RemoteCall(this.moduleName,"DataLatteUa","recordUpdate",{name:this.recordType,id:this.recordId,fields:values});
return call};Object.defineProperty(DataRecord.prototype,"moduleName",{get:function(){return this._moduleName},set:function(value){this._moduleName=value},enumerable:true,configurable:true});Object.defineProperty(DataRecord.prototype,"formCreating",{get:function(){if(!this._formCreating)this._formCreating=new latte.LatteEvent(this);return this._formCreating},enumerable:true,configurable:true});Object.defineProperty(DataRecord.prototype,"formCreated",{get:function(){if(!this._formCreated)this._formCreated=
new latte.LatteEvent(this);return this._formCreated},enumerable:true,configurable:true});Object.defineProperty(DataRecord.prototype,"recordId",{get:function(){return this._recordId},set:function(value){this._recordId=value},enumerable:true,configurable:true});Object.defineProperty(DataRecord.prototype,"recordType",{get:function(){return this._recordType},set:function(value){this._recordType=value},enumerable:true,configurable:true});Object.defineProperty(DataRecord.prototype,"tag",{get:function(){return this._tag},
set:function(value){this._tag=value},enumerable:true,configurable:true});Object.defineProperty(DataRecord.prototype,"viewCreated",{get:function(){if(!this._viewCreated)this._viewCreated=new latte.LatteEvent(this);return this._viewCreated},enumerable:true,configurable:true});Object.defineProperty(DataRecord.prototype,"viewCreating",{get:function(){if(!this._viewCreating)this._viewCreating=new latte.LatteEvent(this);return this._viewCreating},enumerable:true,configurable:true});DataRecord.recordsNamespaceName=
"latte";return DataRecord}();latte.DataRecord=DataRecord})(latte||(latte={}));var latte;
(function(latte){var DataRecordCollection=function(_super){__extends(DataRecordCollection,_super);function DataRecordCollection(addCallback,removeCallback,context){if(typeof addCallback==="undefined")addCallback=null;if(typeof removeCallback==="undefined")removeCallback=null;if(typeof context==="undefined")context=null;_super.call(this,addCallback,removeCallback,context)}DataRecordCollection.prototype.byId=function(id){return null};return DataRecordCollection}(latte.Collection);latte.DataRecordCollection=
DataRecordCollection})(latte||(latte={}));var latte;
(function(latte){var DataSet=function(){function DataSet(){this.columns=new latte.Collection;this.rows=new latte.Collection}DataSet.fromServerObject=function(dataset){var d=new DataSet;var i;for(i in dataset.fields)d.columns.add(new latte.DataSetColumn(dataset.fields[i].name,DataSet.fromServerType(dataset.fields[i].type),dataset.fields[i].length));if(latte._isArray(dataset.rows))for(i=0;i<dataset.rows.length;i++){var arr=dataset.rows[i];var ds=new latte.DataSetRow(arr);d.rows.add(ds)}return d};DataSet.fromServerType=
function(type){switch(type){case "int":type="integer";break;case "blob":type="string";break}return type};DataSet.prototype.getColumnIndex=function(columnName){var col=null;var i=0;while(col=this.columns.next()){if(col.name.toLowerCase()==columnName.toLowerCase()){this.columns.resetPointer();return i}i++}return null};DataSet.prototype.getDataArray=function(){var a=[];for(var i=0;i<this.rows.count;i++)a.push(this.rows.item(i).getDataArray(this.columns.count));return a};DataSet.prototype.getValue=function(columnName,
rowIndex){var columnIndex;if(columnIndex=this.getColumnIndex(columnName))return this.getValueAt(columnIndex,rowIndex);else throw new latte.InvalidArgumentEx(columnName);};DataSet.prototype.getValueAt=function(columnIndex,rowIndex){if(this.rows.count>rowIndex&&this.rows.item(rowIndex).hasValueAt(columnIndex))return this.rows.item(rowIndex).getValueAt(columnIndex);else return null};DataSet.prototype.setValue=function(columnName,rowIndex,value){var columnIndex;if(columnIndex=this.getColumnIndex(columnName))return this.setValueAt(columnIndex,
rowIndex,value);return this};DataSet.prototype.setValueAt=function(columnIndex,rowIndex,value){if(this.rows.count>rowIndex&&this.rows.item(rowIndex).hasValueAt(columnIndex))this.rows.item(rowIndex).setValueAt(columnIndex,value);else if(this.rows.count<=rowIndex)throw new latte.InvalidArgumentEx("rowIndex",rowIndex);else throw new latte.InvalidArgumentEx("columnIndex",columnIndex);return this};return DataSet}();latte.DataSet=DataSet})(latte||(latte={}));var latte;
(function(latte){var Message=function(){function Message(moduleName,className,method,arguments,id){if(typeof moduleName==="undefined")moduleName=null;if(typeof className==="undefined")className=null;if(typeof method==="undefined")method=null;if(typeof arguments==="undefined")arguments=null;if(typeof id==="undefined")id=0;this._calls=[];if(className!==null)this.calls.push(new latte.RemoteCall(moduleName,className,method,arguments,id));if(Message._pendentMessages===null)Message._pendentMessages=new latte.Collection}
Message.sendCalls=function(calls){var m=new Message;m.addCalls(calls);m.send();return m};Object.defineProperty(Message,"networkAvailable",{get:function(){return Message._networkAvailable},enumerable:true,configurable:true});Message.prototype.addCalls=function(calls){this._calls=this._calls.concat(calls)};Message.prototype.dataArrived=function(data){var parsed=false;var result=null;this._working=false;this.response=data;Message._networkAvailable=true;this.onResponseArrived();if(data.length==0)this.onFailed("Empty response from server");
try{result=jQuery.parseJSON(data);parsed=true}catch(ex){}if(parsed&&latte._isArray(result)){if(result.length!==this.calls.length)this.onFailed("Different amount of response than calls");for(var i=0;i<this.calls.length;i++)this.calls[i].respond(result[i])}else this.onFailed("Can't parse or response is not an array.");if(Message.networkAvailable){if(!Message._pendentMessages)Message._pendentMessages=new latte.Collection;Message._pendentMessages.each(function(m){m.send()});Message._pendentMessages.clear()}};
Message.prototype.onFailed=function(errorDescription){latte.log(errorDescription);latte.log("On call(s):");for(var i=0;i<this.calls.length;i++)latte.log(this.calls[i].toString());latte.log(this.response);if(this._failed instanceof latte.LatteEvent)this.failed.raise();if(latte._isFunction(Message.globalFailed))Message.globalFailed.call(this,errorDescription)};Message.prototype.onNetworkFailed=function(){Message._networkAvailable=false;if(Message._retryLeader===null)Message._retryLeader=this;else if(Message._retryLeader!==
this){Message._pendentMessages.add(this);return}if(this._networkFailed)this._networkFailed.raise();if(!(Message._retryLoader instanceof latte.Loader))Message._retryLoader=new latte.Loader(strings.reconnecting);if(this.critical);if(Message._retryTime==0)Message._retryTime=5;else Message._retryTime=Math.min(latte.TimeSpan.fromMinutes(5).totalSeconds,Message._retryTime*2);Message._retryCountdown=Message._retryTime;Message._retryLoader.text=latte.sprintf(strings.reconnectingInS,latte.TimeSpan.fromSeconds(Message._retryCountdown).toString());
if(Message._retryTimer)Message._retryTimer.pause();Message._retryTimer=new latte.Timer(function(){Message._retryCountdown--;if(Message._retryCountdown==0){Message._retryLoader.text=strings.reconnecting;Message._networkAvailable=true;this.send()}else if(Message._retryCountdown<0){Message._retryTimer.pause();Message._retryLoader.stop()}else Message._retryLoader.text=latte.sprintf(strings.reconnectingInS,latte.TimeSpan.fromSeconds(Message._retryCountdown).toString())},1E3,this);Message._retryTimer.start()};
Message.prototype.onResponseArrived=function(){if(this._loader instanceof latte.Loader)this._loader.stop();if(this._responseArrived)this.responseArrived.raise()};Message.prototype.onSent=function(){if(this._sent)this.sent.raise();Message.log.push(this);if(Message.log.length>50)Message.log.shift()};Message.prototype.send=function(success,failure){if(typeof success==="undefined")success=null;if(typeof failure==="undefined")failure=null;if(!Message.networkAvailable){Message._pendentMessages.add(this);
return this}if(success||failure)if(this.calls.length!==1)throw new latte.Ex("Can't assign handlers when more than one call in message");else{if(success)this.calls[0].success.add(success);if(failure)this.calls[0].failure.add(failure)}this._working=true;this.showLoader();var calls=[];for(var i=0;i<this.calls.length;i++)calls.push(this.calls[i].marshall());$.ajax({url:Message.pathToRequest,context:this,data:{action:"ajax-rpc",calls:JSON.stringify(calls)},dataType:"text",type:"POST",success:function(data){this.dataArrived(data)},
error:function(jqXHR,textStatus,errorThrown){this._working=false;this.errorDescription="Network error: "+textStatus;this.errorCode=1;this.onNetworkFailed()}});this.onSent();return this};Message.prototype.showLoader=function(){if(this.loaderText)this._loader=new latte.Loader(this.loaderText)};Message.prototype.working=function(){return this._working};Object.defineProperty(Message.prototype,"calls",{get:function(){return this._calls},enumerable:true,configurable:true});Object.defineProperty(Message.prototype,
"failed",{get:function(){if(!this._failed)this._failed=new latte.LatteEvent(this);return this._failed},enumerable:true,configurable:true});Object.defineProperty(Message.prototype,"loaderText",{get:function(){return this._loaderText},set:function(value){this._loaderText=value;if(this.working())this.showLoader()},enumerable:true,configurable:true});Object.defineProperty(Message.prototype,"networkFailed",{get:function(){if(!this._networkFailed)this._networkFailed=new latte.LatteEvent(this);return this._networkFailed},
enumerable:true,configurable:true});Object.defineProperty(Message.prototype,"responseArrived",{get:function(){if(!this._responseArrived)this._responseArrived=new latte.LatteEvent(this);return this._responseArrived},enumerable:true,configurable:true});Object.defineProperty(Message.prototype,"sent",{get:function(){if(!this._sent)this._sent=new latte.LatteEvent(this);return this._sent},enumerable:true,configurable:true});Message.log=[];Message._networkAvailable=true;Message._pendentMessages=null;Message.pathToRequest=
"/datalatte-files/request.php";return Message}();latte.Message=Message})(latte||(latte={}));var latte;
(function(latte){var RemoteCall=function(){function RemoteCall(moduleName,className,method,params,id,returns){if(typeof moduleName==="undefined")moduleName=null;if(typeof className==="undefined")className=null;if(typeof method==="undefined")method=null;if(typeof params==="undefined")params=null;if(typeof id==="undefined")id=0;if(typeof returns==="undefined")returns=null;this._className=null;this._method=null;this._id=0;this._params=null;this._returns=null;this._success=null;this._failure=null;this._something=
null;this._moduleName=null;if(moduleName)this.moduleName=moduleName;if(className)this.className=className;if(method)this.method=method;if(params)this.params=params;if(id)this.id=id;if(returns)this.returns=returns}RemoteCall.prototype.marshall=function(){return{moduleName:this.moduleName,className:this.className,method:this.method,id:this.id,params:this.params}};RemoteCall.prototype.onFailure=function(){if(this._failure instanceof latte.LatteEvent)this._failure.raise()};RemoteCall.prototype.onSuccess=
function(data){if(this._success instanceof latte.LatteEvent)this._success.raise(data)};RemoteCall.prototype.respond=function(responseData){var response=new latte.RemoteResponse(this,responseData);this.response=response};RemoteCall.prototype.send=function(success,failure){if(typeof success==="undefined")success=null;if(typeof failure==="undefined")failure=null;this.withHandlers(success,failure);var m=new latte.Message;m.calls.push(this);m.send();return m};RemoteCall.prototype.sendWithLoader=function(loaderText,
success,failure){if(typeof success==="undefined")success=null;if(typeof failure==="undefined")failure=null;var m=this.send(success,failure);m.loaderText=loaderText;return m};RemoteCall.prototype.toString=function(){var idpart=this.id>0?latte.sprintf("<%s>",this.id):"";var paramspart=[];for(var i in this.params){var a=this.params[i];paramspart.push(i+" = "+(latte._isArray(a)||latte._isObject(a)?JSON.stringify(a):String(a)))}return latte.sprintf("%s%s.%s(%s)",this.className,idpart,this.method,paramspart.join(", "))};
RemoteCall.prototype.withHandlers=function(success,failure){if(typeof success==="undefined")success=null;if(typeof failure==="undefined")failure=null;if(success)this.success.add(success);if(failure)this.failure.add(failure);return this};Object.defineProperty(RemoteCall.prototype,"className",{get:function(){return this._className},set:function(value){this._className=value},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,"method",{get:function(){return this._method},set:function(value){this._method=
value},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,"failure",{get:function(){if(!(this._failure instanceof latte.LatteEvent))this._failure=new latte.LatteEvent(this);return this._failure},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,"something",{get:function(){return this._something},set:function(value){this._something=value},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,"moduleName",{get:function(){return this._moduleName},
set:function(value){this._moduleName=value},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,"id",{get:function(){return this._id},set:function(value){this._id=value},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,"params",{get:function(){return this._params},set:function(value){this._params=value},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,"response",{get:function(){return this._response},set:function(value){this._response=
value;if(value.logs.length>0){latte.log(latte.sprintf("Log: "+this.toString()));for(var i=0;i<value.logs.length;i++)latte.log("    "+value.logs[i])}if(value.warnings.length>0){latte.log("Warnings: "+latte.sprintf(this.toString()));for(var i=0;i<value.warnings.length;i++)if(console&&console.warn)console.warn("    "+value.warnings[i]);else latte.log("    "+value.warnings[i])}if(value.success)this.onSuccess(value.data);else this.onFailure()},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,
"returns",{get:function(){return this._returns},set:function(value){this._returns=value},enumerable:true,configurable:true});Object.defineProperty(RemoteCall.prototype,"success",{get:function(){if(!(this._success instanceof latte.LatteEvent))this._success=new latte.LatteEvent(this);return this._success},enumerable:true,configurable:true});return RemoteCall}();latte.RemoteCall=RemoteCall})(latte||(latte={}));var latte;
(function(latte){var RemoteResponse=function(){function RemoteResponse(call,response){this._call=null;this._errorCode=-1;this._errorDescription=null;this._success=false;this._logs=[];this._warnings=[];this._call=call;this._response=response;this.unmarshall()}RemoteResponse.prototype.unmarshall=function(){for(var i in this.response)this["_"+i]=this.response[i];if(this.success===true)this._data=latte.DataRecord.scanAndConvert(this.data);else{latte.log("Error on call: "+this.call.toString());latte.log(latte.sprintf("(%s) - %s",
this.errorCode,this.errorDescription));this.call.onFailure()}};Object.defineProperty(RemoteResponse.prototype,"call",{get:function(){return this._call},enumerable:true,configurable:true});Object.defineProperty(RemoteResponse.prototype,"errorCode",{get:function(){return this._errorCode},enumerable:true,configurable:true});Object.defineProperty(RemoteResponse.prototype,"errorDescription",{get:function(){return this._errorDescription},enumerable:true,configurable:true});Object.defineProperty(RemoteResponse.prototype,
"logs",{get:function(){return this._logs},set:function(value){this._logs=value},enumerable:true,configurable:true});Object.defineProperty(RemoteResponse.prototype,"response",{get:function(){return this._response},enumerable:true,configurable:true});Object.defineProperty(RemoteResponse.prototype,"data",{get:function(){return this._data},enumerable:true,configurable:true});Object.defineProperty(RemoteResponse.prototype,"success",{get:function(){return this._success},enumerable:true,configurable:true});
Object.defineProperty(RemoteResponse.prototype,"warnings",{get:function(){return this._warnings},set:function(value){this._warnings=value},enumerable:true,configurable:true});return RemoteResponse}();latte.RemoteResponse=RemoteResponse})(latte||(latte={}));var latte;
(function(latte){var DataRecordDialogView=function(_super){__extends(DataRecordDialogView,_super);function DataRecordDialogView(record){if(typeof record==="undefined")record=null;_super.call(this);var dialog=this;this.saving=new latte.LatteEvent(this);this.saved=new latte.LatteEvent(this);this.formView=new latte.DataRecordFormView(record);this.saveButton=new latte.ButtonItem;this.saveButton.text=strings.save;this.saveButton.click.add(function(){dialog.onSaving()});this.cancelButton=new latte.ButtonItem;
this.cancelButton.text=strings.cancel;this.view=this.formView;this.items.add(this.saveButton);this.items.add(this.cancelButton)}DataRecordDialogView.prototype.onSaved=function(){this.saved.raise()};DataRecordDialogView.prototype.onSaving=function(){var ptr=this;this.formView.applyValues();this.record.save(function(){ptr.onSaved()});this.saving.raise()};Object.defineProperty(DataRecordDialogView.prototype,"readOnly",{get:function(){return this._readOnly},set:function(value){this._readOnly=value;for(var i=
0;i<this.formView.inputs.count;i++)this.formView.inputs.item(i).readOnly=value;if(value){this.saveButton.visible=false;this.cancelButton.text=strings.close}else{this.saveButton.visible=true;this.cancelButton.text=strings.cancel}},enumerable:true,configurable:true});Object.defineProperty(DataRecordDialogView.prototype,"record",{get:function(){return this.formView.record},enumerable:true,configurable:true});return DataRecordDialogView}(latte.DialogView);latte.DataRecordDialogView=DataRecordDialogView})(latte||
(latte={}));var latte;
(function(latte){var DataRecordFormItem=function(_super){__extends(DataRecordFormItem,_super);function DataRecordFormItem(record){if(typeof record==="undefined")record=null;_super.call(this);if(record)this.record=record}DataRecordFormItem.prototype.applyValues=function(record){if(typeof record==="undefined")record=null;var input;var r=record||this.record;while(input=this.inputs.next()){if(input.readOnly===true)continue;r[input.tag]=input.value}};Object.defineProperty(DataRecordFormItem.prototype,"record",
{get:function(){return this._record},set:function(record){var calls=[];this._record=record;this.inputs.clear();if(record){record.onFormCreating(this);var metadata=record.getMetadata();if(metadata&&metadata.fields)for(var i in metadata.fields){var field=metadata.fields[i];var input=new latte.InputItem;var value=record[i]?record[i]:null;input.text=field.text?field.text:"(No name)";input.type=field.type?field.type:"string";input.name=i;input.tag=i;input.readOnly=field["readonly"]===true;input.visible=
field["visible"]!==false;input.options=field["options"];input.value=value;input.separator=field["separator"]===true;if(field.type=="record"){var d=input.valueItem;d.loaderFunction=field.loaderFunction;if(value&&field["recordType"]&&!(value instanceof latte.DataRecord))(function(d,input){calls.push((new latte.RemoteCall("_core","DataLatteUa","recordSelect",{name:field["recordType"],id:value})).withHandlers(function(r){if(r&&r.recordId){d.setRecordSilent(r);input.value=input.value}}))})(d,input)}this.inputs.add(input)}record.onFormCreated(this);
if(calls.length>0)latte.Message.sendCalls(calls)}},enumerable:true,configurable:true});return DataRecordFormItem}(latte.FormItem);latte.DataRecordFormItem=DataRecordFormItem})(latte||(latte={}));var latte;
(function(latte){var DataRecordFormView=function(_super){__extends(DataRecordFormView,_super);function DataRecordFormView(record){if(typeof record==="undefined")record=null;_super.call(this);this.form=new latte.DataRecordFormItem;this.items.clear();this.items.add(this.form);if(record)this.record=record}DataRecordFormView.prototype.applyValues=function(record){if(typeof record==="undefined")record=null;this.form.applyValues(record)};Object.defineProperty(DataRecordFormView.prototype,"record",{get:function(){return this.form.record},
set:function(record){this.form.record=record},enumerable:true,configurable:true});return DataRecordFormView}(latte.FormView);latte.DataRecordFormView=DataRecordFormView})(latte||(latte={}));var latte;
(function(latte){var DataRecordGridView=function(_super){__extends(DataRecordGridView,_super);function DataRecordGridView(){_super.call(this);this.records=new latte.Collection(this._onAddRecord,this._onRemoveRecord,this)}DataRecordGridView.prototype._onAddRecord=function(record){var row=new latte.GridViewRow;var colIndex=0;var col=null;if(this.records.count===1){this.columns.clear();var metadata=record.getMetadata();if(metadata&&metadata.fields){for(var i in metadata.fields){var f=metadata.fields[i];
var c=new latte.GridViewColumn;c.name=f.text||i;c.type=f.type||"string";this.columns.add(c)}this.recordType=record.recordType;this._metadata=metadata;this.allowNewRows=metadata["can-insert"]===true}}while(col=this.columns.next()){row.setValueAt(colIndex,record[col.tag]);colIndex++}row.tag=record;row.readOnly=this._metadata["can-update"]!==true;record.tags._recordDataGridViewRow=row;this.rows.add(row)};DataRecordGridView.prototype._onRemoveRecord=function(record){if(!(record.tags._recordDataGridViewRow instanceof
latte.DataSetRow))throw new latte.Ex;this.rows.remove(record.tags._recordDataGridViewRow)};DataRecordGridView.prototype.applyValues=function(row,record){for(var i=0;i<this.columns.count;i++){var column=this.columns.item(i);var name=column.tag;record[name]=row.hasValueAt(i)?row.getValueAt(i):null}};DataRecordGridView.prototype.onContextItemsShow=function(){_super.prototype.onContextItemsShow.call(this);var cell=this.selectedCell;var row=this.rows.item(cell.data("rowIndex"));var record=row?row.tag:
null;var meta=record?record.getMetadata():null;this._actionRemoveRow.enabled=meta&&meta["can-delete"]===true};DataRecordGridView.prototype.onRowsAdded=function(dataset){_super.prototype.onRowsAdded.call(this,dataset);for(var i=0;i<dataset.rows.count;i++){var row=dataset.rows.item(i);var record=new latte.DataRecord;record.recordType=this.recordType;record.metadata=this._metadata;this.applyValues(row,record);row.tag=record;record.insert(function(){latte.sprintf("Inserted: "+record.recordId)})}this.confirmRowsAdded()};
DataRecordGridView.prototype.onRowsChanged=function(dataset){_super.prototype.onRowsChanged.call(this,dataset);for(var i=0;i<dataset.rows.count;i++){var row=dataset.rows.item(i);var record=row.tag;this.applyValues(row,record);record.update(function(){latte.sprintf("Updated: "+record.recordId)})}this.confirmRowsChanged()};DataRecordGridView.prototype.onRowsRemoved=function(dataset){_super.prototype.onRowsRemoved.call(this,dataset);for(var i=0;i<dataset.rows.count;i++){var row=dataset.rows.item(i);
var record=row.tag;record.remove(function(){latte.sprintf("Removed: "+record.recordId)})}this.confirmRowsRemoved()};Object.defineProperty(DataRecordGridView.prototype,"recordType",{get:function(){return this._recordType},set:function(value){this._recordType=value},enumerable:true,configurable:true});return DataRecordGridView}(latte.GridView);latte.DataRecordGridView=DataRecordGridView})(latte||(latte={}));var latte;
(function(latte){var DataRecordValueItem=function(_super){__extends(DataRecordValueItem,_super);function DataRecordValueItem(loader,textboxCreated){if(typeof loader==="undefined")loader=null;if(typeof textboxCreated==="undefined")textboxCreated=null;_super.call(this);this._loaderFunction=null;this._record=null;if(textboxCreated)this.textboxCreated.add(textboxCreated);this.updateItem();if(loader)this.loaderFunction=loader}DataRecordValueItem.prototype.getValue=function(){if(this.record)return this.record.recordId;
else return 0};DataRecordValueItem.prototype.getValueString=function(){if(this.record)return this.record.toString();else return""};DataRecordValueItem.prototype.setValue=function(value){if(value instanceof latte.DataRecord)this.record=value};DataRecordValueItem.prototype.setRecordSilent=function(r){this._record=r;this.updateItem()};DataRecordValueItem.prototype.updateItem=function(){var _this=this;this.element.empty();if(this.record){this._textbox=null;var icon=latte._isFunction(this.record["icon16"])?
this.record["icon16"]():null;var bg=new latte.ButtonGroupItem([new latte.ButtonItem(this.record.toString(),icon),new latte.ButtonItem(null,latte.Glyph.dismiss,function(){var txt=_this.text;_this.record=null;_this.textbox.input.select();_this.textbox.input.focus()})]);bg.appendTo(this)}else{this._textbox=new latte.TextboxItem;this.textbox.appendTo(this);this.textbox.filterSuggestions.add(function(){if(_this.loaderFunction)_this.loaderFunction(_this,function(items){_this.textbox.suggestions.clear();
_this.textbox.suggestions.addArray(items)})});this.onTextboxCreated()}this.element.clear()};Object.defineProperty(DataRecordValueItem.prototype,"textboxCreated",{get:function(){if(!this._textboxCreated)this._textboxCreated=new latte.LatteEvent(this);return this._textboxCreated},enumerable:true,configurable:true});DataRecordValueItem.prototype.onTextboxCreated=function(){if(this._textboxCreated)this._textboxCreated.raise(this.textbox)};Object.defineProperty(DataRecordValueItem.prototype,"loaderFunction",
{get:function(){return this._loaderFunction},set:function(value){this._loaderFunction=value},enumerable:true,configurable:true});Object.defineProperty(DataRecordValueItem.prototype,"record",{get:function(){return this._record},set:function(value){var changed=value!==this._record;this._record=value;this.updateItem();if(changed)this.onValueChanged()},enumerable:true,configurable:true});Object.defineProperty(DataRecordValueItem.prototype,"textbox",{get:function(){return this._textbox},enumerable:true,
configurable:true});Object.defineProperty(DataRecordValueItem.prototype,"text",{get:function(){if(this._textbox)return this._textbox.value;else if(this.record)return this.record.toString();return null},enumerable:true,configurable:true});return DataRecordValueItem}(latte.ValueItem);latte.DataRecordValueItem=DataRecordValueItem})(latte||(latte={}));var latte;
(function(latte){var GridViewColumn=function(_super){__extends(GridViewColumn,_super);function GridViewColumn(name,type,length){if(typeof name==="undefined")name="";if(typeof type==="undefined")type="";if(typeof length==="undefined")length=0;_super.call(this);if(name)this.name=name;if(type)this.type=type;if(length)this.length=length}Object.defineProperty(GridViewColumn.prototype,"header",{get:function(){return this._header},set:function(value){this._header=value},enumerable:true,configurable:true});
Object.defineProperty(GridViewColumn.prototype,"readOnly",{get:function(){return this._readonly},set:function(value){this._readonly=value},enumerable:true,configurable:true});return GridViewColumn}(latte.DataSetColumn);latte.GridViewColumn=GridViewColumn})(latte||(latte={}));var latte;
(function(latte){var GridViewRow=function(_super){__extends(GridViewRow,_super);function GridViewRow(data){if(typeof data==="undefined")data=[];_super.call(this,data)}return GridViewRow}(latte.DataSetRow);latte.GridViewRow=GridViewRow})(latte||(latte={}));