module latte {

    /**
     *
     */
    export class Linear {

        //region Static
        static get home2(): LinearIcon { return LinearIcon.byCatalog("home2"); }
        static get home(): LinearIcon { return LinearIcon.byCatalog("home"); }
        static get home3(): LinearIcon { return LinearIcon.byCatalog("home3"); }
        static get home5(): LinearIcon { return LinearIcon.byCatalog("home5"); }
        static get home4(): LinearIcon { return LinearIcon.byCatalog("home4"); }
        static get home6(): LinearIcon { return LinearIcon.byCatalog("home6"); }
        static get toothbrush(): LinearIcon { return LinearIcon.byCatalog("toothbrush"); }
        static get bathtub(): LinearIcon { return LinearIcon.byCatalog("bathtub"); }
        static get bed(): LinearIcon { return LinearIcon.byCatalog("bed"); }
        static get chair(): LinearIcon { return LinearIcon.byCatalog("chair"); }
        static get couch(): LinearIcon { return LinearIcon.byCatalog("couch"); }
        static get city(): LinearIcon { return LinearIcon.byCatalog("city"); }
        static get pencil(): LinearIcon { return LinearIcon.byCatalog("pencil"); }
        static get apartment(): LinearIcon { return LinearIcon.byCatalog("apartment"); }
        static get pencil2(): LinearIcon { return LinearIcon.byCatalog("pencil2"); }
        static get pencil3(): LinearIcon { return LinearIcon.byCatalog("pencil3"); }
        static get pen(): LinearIcon { return LinearIcon.byCatalog("pen"); }
        static get eraser(): LinearIcon { return LinearIcon.byCatalog("eraser"); }
        static get pencil5(): LinearIcon { return LinearIcon.byCatalog("pencil5"); }
        static get pencil4(): LinearIcon { return LinearIcon.byCatalog("pencil4"); }
        static get feather(): LinearIcon { return LinearIcon.byCatalog("feather"); }
        static get feather3(): LinearIcon { return LinearIcon.byCatalog("feather3"); }
        static get feather2(): LinearIcon { return LinearIcon.byCatalog("feather2"); }
        static get pen2(): LinearIcon { return LinearIcon.byCatalog("pen2"); }
        static get pen_remove(): LinearIcon { return LinearIcon.byCatalog("pen-remove"); }
        static get pen_add(): LinearIcon { return LinearIcon.byCatalog("pen-add"); }
        static get vector(): LinearIcon { return LinearIcon.byCatalog("vector"); }
        static get blog(): LinearIcon { return LinearIcon.byCatalog("blog"); }
        static get pen3(): LinearIcon { return LinearIcon.byCatalog("pen3"); }
        static get brush(): LinearIcon { return LinearIcon.byCatalog("brush"); }
        static get spray(): LinearIcon { return LinearIcon.byCatalog("spray"); }
        static get brush2(): LinearIcon { return LinearIcon.byCatalog("brush2"); }
        static get paint_roller(): LinearIcon { return LinearIcon.byCatalog("paint-roller"); }
        static get tape(): LinearIcon { return LinearIcon.byCatalog("tape"); }
        static get stamp(): LinearIcon { return LinearIcon.byCatalog("stamp"); }
        static get desk_tape(): LinearIcon { return LinearIcon.byCatalog("desk-tape"); }
        static get eye_dropper(): LinearIcon { return LinearIcon.byCatalog("eye-dropper"); }
        static get texture(): LinearIcon { return LinearIcon.byCatalog("texture"); }
        static get palette(): LinearIcon { return LinearIcon.byCatalog("palette"); }
        static get bucket(): LinearIcon { return LinearIcon.byCatalog("bucket"); }
        static get color_sampler(): LinearIcon { return LinearIcon.byCatalog("color-sampler"); }
        static get gradient(): LinearIcon { return LinearIcon.byCatalog("gradient"); }
        static get magic_wand(): LinearIcon { return LinearIcon.byCatalog("magic-wand"); }
        static get gradient2(): LinearIcon { return LinearIcon.byCatalog("gradient2"); }
        static get magnet(): LinearIcon { return LinearIcon.byCatalog("magnet"); }
        static get pencil_ruler2(): LinearIcon { return LinearIcon.byCatalog("pencil-ruler2"); }
        static get pencil_ruler(): LinearIcon { return LinearIcon.byCatalog("pencil-ruler"); }
        static get compass(): LinearIcon { return LinearIcon.byCatalog("compass"); }
        static get gun(): LinearIcon { return LinearIcon.byCatalog("gun"); }
        static get aim(): LinearIcon { return LinearIcon.byCatalog("aim"); }
        static get bottle(): LinearIcon { return LinearIcon.byCatalog("bottle"); }
        static get drop_crossed(): LinearIcon { return LinearIcon.byCatalog("drop-crossed"); }
        static get drop(): LinearIcon { return LinearIcon.byCatalog("drop"); }
        static get drop2(): LinearIcon { return LinearIcon.byCatalog("drop2"); }
        static get snow2(): LinearIcon { return LinearIcon.byCatalog("snow2"); }
        static get snow(): LinearIcon { return LinearIcon.byCatalog("snow"); }
        static get fire(): LinearIcon { return LinearIcon.byCatalog("fire"); }
        static get knife(): LinearIcon { return LinearIcon.byCatalog("knife"); }
        static get lighter(): LinearIcon { return LinearIcon.byCatalog("lighter"); }
        static get dagger(): LinearIcon { return LinearIcon.byCatalog("dagger"); }
        static get toilet_paper(): LinearIcon { return LinearIcon.byCatalog("toilet-paper"); }
        static get tissue(): LinearIcon { return LinearIcon.byCatalog("tissue"); }
        static get poop(): LinearIcon { return LinearIcon.byCatalog("poop"); }
        static get umbrella(): LinearIcon { return LinearIcon.byCatalog("umbrella"); }
        static get umbrella2(): LinearIcon { return LinearIcon.byCatalog("umbrella2"); }
        static get rain(): LinearIcon { return LinearIcon.byCatalog("rain"); }
        static get tornado(): LinearIcon { return LinearIcon.byCatalog("tornado"); }
        static get wind(): LinearIcon { return LinearIcon.byCatalog("wind"); }
        static get fan(): LinearIcon { return LinearIcon.byCatalog("fan"); }
        static get contrast(): LinearIcon { return LinearIcon.byCatalog("contrast"); }
        static get sun_small(): LinearIcon { return LinearIcon.byCatalog("sun-small"); }
        static get sun(): LinearIcon { return LinearIcon.byCatalog("sun"); }
        static get sun2(): LinearIcon { return LinearIcon.byCatalog("sun2"); }
        static get moon(): LinearIcon { return LinearIcon.byCatalog("moon"); }
        static get cloud(): LinearIcon { return LinearIcon.byCatalog("cloud"); }
        static get cloud_upload(): LinearIcon { return LinearIcon.byCatalog("cloud-upload"); }
        static get cloud_download(): LinearIcon { return LinearIcon.byCatalog("cloud-download"); }
        static get cloud_rain(): LinearIcon { return LinearIcon.byCatalog("cloud-rain"); }
        static get cloud_hailstones(): LinearIcon { return LinearIcon.byCatalog("cloud-hailstones"); }
        static get cloud_snow(): LinearIcon { return LinearIcon.byCatalog("cloud-snow"); }
        static get cloud_windy(): LinearIcon { return LinearIcon.byCatalog("cloud-windy"); }
        static get sun_wind(): LinearIcon { return LinearIcon.byCatalog("sun-wind"); }
        static get cloud_fog(): LinearIcon { return LinearIcon.byCatalog("cloud-fog"); }
        static get cloud_sun(): LinearIcon { return LinearIcon.byCatalog("cloud-sun"); }
        static get cloud_lightning(): LinearIcon { return LinearIcon.byCatalog("cloud-lightning"); }
        static get cloud_sync(): LinearIcon { return LinearIcon.byCatalog("cloud-sync"); }
        static get cloud_lock(): LinearIcon { return LinearIcon.byCatalog("cloud-lock"); }
        static get cloud_gear(): LinearIcon { return LinearIcon.byCatalog("cloud-gear"); }
        static get cloud_alert(): LinearIcon { return LinearIcon.byCatalog("cloud-alert"); }
        static get cloud_check(): LinearIcon { return LinearIcon.byCatalog("cloud-check"); }
        static get cloud_cross(): LinearIcon { return LinearIcon.byCatalog("cloud-cross"); }
        static get cloud_crossed(): LinearIcon { return LinearIcon.byCatalog("cloud-crossed"); }
        static get cloud_database(): LinearIcon { return LinearIcon.byCatalog("cloud-database"); }
        static get database(): LinearIcon { return LinearIcon.byCatalog("database"); }
        static get database_add(): LinearIcon { return LinearIcon.byCatalog("database-add"); }
        static get database_remove(): LinearIcon { return LinearIcon.byCatalog("database-remove"); }
        static get database_lock(): LinearIcon { return LinearIcon.byCatalog("database-lock"); }
        static get database_refresh(): LinearIcon { return LinearIcon.byCatalog("database-refresh"); }
        static get database_check(): LinearIcon { return LinearIcon.byCatalog("database-check"); }
        static get database_history(): LinearIcon { return LinearIcon.byCatalog("database-history"); }
        static get database_upload(): LinearIcon { return LinearIcon.byCatalog("database-upload"); }
        static get database_download(): LinearIcon { return LinearIcon.byCatalog("database-download"); }
        static get server(): LinearIcon { return LinearIcon.byCatalog("server"); }
        static get shield(): LinearIcon { return LinearIcon.byCatalog("shield"); }
        static get shield_check(): LinearIcon { return LinearIcon.byCatalog("shield-check"); }
        static get shield_alert(): LinearIcon { return LinearIcon.byCatalog("shield-alert"); }
        static get shield_cross(): LinearIcon { return LinearIcon.byCatalog("shield-cross"); }
        static get lock(): LinearIcon { return LinearIcon.byCatalog("lock"); }
        static get rotation_lock(): LinearIcon { return LinearIcon.byCatalog("rotation-lock"); }
        static get unlock(): LinearIcon { return LinearIcon.byCatalog("unlock"); }
        static get key(): LinearIcon { return LinearIcon.byCatalog("key"); }
        static get key_hole(): LinearIcon { return LinearIcon.byCatalog("key-hole"); }
        static get toggle_off(): LinearIcon { return LinearIcon.byCatalog("toggle-off"); }
        static get toggle_on(): LinearIcon { return LinearIcon.byCatalog("toggle-on"); }
        static get cog(): LinearIcon { return LinearIcon.byCatalog("cog"); }
        static get cog2(): LinearIcon { return LinearIcon.byCatalog("cog2"); }
        static get wrench(): LinearIcon { return LinearIcon.byCatalog("wrench"); }
        static get screwdriver(): LinearIcon { return LinearIcon.byCatalog("screwdriver"); }
        static get hammer_wrench(): LinearIcon { return LinearIcon.byCatalog("hammer-wrench"); }
        static get hammer(): LinearIcon { return LinearIcon.byCatalog("hammer"); }
        static get saw(): LinearIcon { return LinearIcon.byCatalog("saw"); }
        static get axe(): LinearIcon { return LinearIcon.byCatalog("axe"); }
        static get axe2(): LinearIcon { return LinearIcon.byCatalog("axe2"); }
        static get shovel(): LinearIcon { return LinearIcon.byCatalog("shovel"); }
        static get pickaxe(): LinearIcon { return LinearIcon.byCatalog("pickaxe"); }
        static get factory(): LinearIcon { return LinearIcon.byCatalog("factory"); }
        static get factory2(): LinearIcon { return LinearIcon.byCatalog("factory2"); }
        static get recycle(): LinearIcon { return LinearIcon.byCatalog("recycle"); }
        static get trash(): LinearIcon { return LinearIcon.byCatalog("trash"); }
        static get trash2(): LinearIcon { return LinearIcon.byCatalog("trash2"); }
        static get trash3(): LinearIcon { return LinearIcon.byCatalog("trash3"); }
        static get broom(): LinearIcon { return LinearIcon.byCatalog("broom"); }
        static get game(): LinearIcon { return LinearIcon.byCatalog("game"); }
        static get gamepad(): LinearIcon { return LinearIcon.byCatalog("gamepad"); }
        static get joystick(): LinearIcon { return LinearIcon.byCatalog("joystick"); }
        static get dice(): LinearIcon { return LinearIcon.byCatalog("dice"); }
        static get spades(): LinearIcon { return LinearIcon.byCatalog("spades"); }
        static get diamonds(): LinearIcon { return LinearIcon.byCatalog("diamonds"); }
        static get clubs(): LinearIcon { return LinearIcon.byCatalog("clubs"); }
        static get hearts(): LinearIcon { return LinearIcon.byCatalog("hearts"); }
        static get heart(): LinearIcon { return LinearIcon.byCatalog("heart"); }
        static get star(): LinearIcon { return LinearIcon.byCatalog("star"); }
        static get star_half(): LinearIcon { return LinearIcon.byCatalog("star-half"); }
        static get star_empty(): LinearIcon { return LinearIcon.byCatalog("star-empty"); }
        static get flag(): LinearIcon { return LinearIcon.byCatalog("flag"); }
        static get flag2(): LinearIcon { return LinearIcon.byCatalog("flag2"); }
        static get flag3(): LinearIcon { return LinearIcon.byCatalog("flag3"); }
        static get mailbox_full(): LinearIcon { return LinearIcon.byCatalog("mailbox-full"); }
        static get mailbox_empty(): LinearIcon { return LinearIcon.byCatalog("mailbox-empty"); }
        static get at_sign(): LinearIcon { return LinearIcon.byCatalog("at-sign"); }
        static get envelope(): LinearIcon { return LinearIcon.byCatalog("envelope"); }
        static get envelope_open(): LinearIcon { return LinearIcon.byCatalog("envelope-open"); }
        static get paperclip(): LinearIcon { return LinearIcon.byCatalog("paperclip"); }
        static get paper_plane(): LinearIcon { return LinearIcon.byCatalog("paper-plane"); }
        static get reply(): LinearIcon { return LinearIcon.byCatalog("reply"); }
        static get reply_all(): LinearIcon { return LinearIcon.byCatalog("reply-all"); }
        static get inbox(): LinearIcon { return LinearIcon.byCatalog("inbox"); }
        static get inbox2(): LinearIcon { return LinearIcon.byCatalog("inbox2"); }
        static get outbox(): LinearIcon { return LinearIcon.byCatalog("outbox"); }
        static get box(): LinearIcon { return LinearIcon.byCatalog("box"); }
        static get archive(): LinearIcon { return LinearIcon.byCatalog("archive"); }
        static get archive2(): LinearIcon { return LinearIcon.byCatalog("archive2"); }
        static get drawers(): LinearIcon { return LinearIcon.byCatalog("drawers"); }
        static get drawers2(): LinearIcon { return LinearIcon.byCatalog("drawers2"); }
        static get drawers3(): LinearIcon { return LinearIcon.byCatalog("drawers3"); }
        static get eye(): LinearIcon { return LinearIcon.byCatalog("eye"); }
        static get eye_crossed(): LinearIcon { return LinearIcon.byCatalog("eye-crossed"); }
        static get eye_plus(): LinearIcon { return LinearIcon.byCatalog("eye-plus"); }
        static get eye_minus(): LinearIcon { return LinearIcon.byCatalog("eye-minus"); }
        static get binoculars(): LinearIcon { return LinearIcon.byCatalog("binoculars"); }
        static get binoculars2(): LinearIcon { return LinearIcon.byCatalog("binoculars2"); }
        static get hdd(): LinearIcon { return LinearIcon.byCatalog("hdd"); }
        static get hdd_down(): LinearIcon { return LinearIcon.byCatalog("hdd-down"); }
        static get hdd_up(): LinearIcon { return LinearIcon.byCatalog("hdd-up"); }
        static get floppy_disk(): LinearIcon { return LinearIcon.byCatalog("floppy-disk"); }
        static get disc(): LinearIcon { return LinearIcon.byCatalog("disc"); }
        static get tape2(): LinearIcon { return LinearIcon.byCatalog("tape2"); }
        static get printer(): LinearIcon { return LinearIcon.byCatalog("printer"); }
        static get shredder(): LinearIcon { return LinearIcon.byCatalog("shredder"); }
        static get file_empty(): LinearIcon { return LinearIcon.byCatalog("file-empty"); }
        static get file_add(): LinearIcon { return LinearIcon.byCatalog("file-add"); }
        static get file_check(): LinearIcon { return LinearIcon.byCatalog("file-check"); }
        static get file_lock(): LinearIcon { return LinearIcon.byCatalog("file-lock"); }
        static get files(): LinearIcon { return LinearIcon.byCatalog("files"); }
        static get copy(): LinearIcon { return LinearIcon.byCatalog("copy"); }
        static get compare(): LinearIcon { return LinearIcon.byCatalog("compare"); }
        static get folder(): LinearIcon { return LinearIcon.byCatalog("folder"); }
        static get folder_search(): LinearIcon { return LinearIcon.byCatalog("folder-search"); }
        static get folder_plus(): LinearIcon { return LinearIcon.byCatalog("folder-plus"); }
        static get folder_minus(): LinearIcon { return LinearIcon.byCatalog("folder-minus"); }
        static get folder_download(): LinearIcon { return LinearIcon.byCatalog("folder-download"); }
        static get folder_upload(): LinearIcon { return LinearIcon.byCatalog("folder-upload"); }
        static get folder_star(): LinearIcon { return LinearIcon.byCatalog("folder-star"); }
        static get folder_heart(): LinearIcon { return LinearIcon.byCatalog("folder-heart"); }
        static get folder_user(): LinearIcon { return LinearIcon.byCatalog("folder-user"); }
        static get folder_shared(): LinearIcon { return LinearIcon.byCatalog("folder-shared"); }
        static get folder_music(): LinearIcon { return LinearIcon.byCatalog("folder-music"); }
        static get folder_picture(): LinearIcon { return LinearIcon.byCatalog("folder-picture"); }
        static get folder_film(): LinearIcon { return LinearIcon.byCatalog("folder-film"); }
        static get scissors(): LinearIcon { return LinearIcon.byCatalog("scissors"); }
        static get paste(): LinearIcon { return LinearIcon.byCatalog("paste"); }
        static get clipboard_empty(): LinearIcon { return LinearIcon.byCatalog("clipboard-empty"); }
        static get clipboard_pencil(): LinearIcon { return LinearIcon.byCatalog("clipboard-pencil"); }
        static get clipboard_text(): LinearIcon { return LinearIcon.byCatalog("clipboard-text"); }
        static get clipboard_check(): LinearIcon { return LinearIcon.byCatalog("clipboard-check"); }
        static get clipboard_down(): LinearIcon { return LinearIcon.byCatalog("clipboard-down"); }
        static get clipboard_left(): LinearIcon { return LinearIcon.byCatalog("clipboard-left"); }
        static get clipboard_alert(): LinearIcon { return LinearIcon.byCatalog("clipboard-alert"); }
        static get clipboard_user(): LinearIcon { return LinearIcon.byCatalog("clipboard-user"); }
        static get register(): LinearIcon { return LinearIcon.byCatalog("register"); }
        static get enter(): LinearIcon { return LinearIcon.byCatalog("enter"); }
        static get exit(): LinearIcon { return LinearIcon.byCatalog("exit"); }
        static get papers(): LinearIcon { return LinearIcon.byCatalog("papers"); }
        static get news(): LinearIcon { return LinearIcon.byCatalog("news"); }
        static get reading(): LinearIcon { return LinearIcon.byCatalog("reading"); }
        static get typewriter(): LinearIcon { return LinearIcon.byCatalog("typewriter"); }
        static get document(): LinearIcon { return LinearIcon.byCatalog("document"); }
        static get document2(): LinearIcon { return LinearIcon.byCatalog("document2"); }
        static get graduation_hat(): LinearIcon { return LinearIcon.byCatalog("graduation-hat"); }
        static get license(): LinearIcon { return LinearIcon.byCatalog("license"); }
        static get license2(): LinearIcon { return LinearIcon.byCatalog("license2"); }
        static get medal_empty(): LinearIcon { return LinearIcon.byCatalog("medal-empty"); }
        static get medal_first(): LinearIcon { return LinearIcon.byCatalog("medal-first"); }
        static get medal_second(): LinearIcon { return LinearIcon.byCatalog("medal-second"); }
        static get medal_third(): LinearIcon { return LinearIcon.byCatalog("medal-third"); }
        static get podium(): LinearIcon { return LinearIcon.byCatalog("podium"); }
        static get trophy(): LinearIcon { return LinearIcon.byCatalog("trophy"); }
        static get trophy2(): LinearIcon { return LinearIcon.byCatalog("trophy2"); }
        static get music_note(): LinearIcon { return LinearIcon.byCatalog("music-note"); }
        static get music_note2(): LinearIcon { return LinearIcon.byCatalog("music-note2"); }
        static get music_note3(): LinearIcon { return LinearIcon.byCatalog("music-note3"); }
        static get playlist(): LinearIcon { return LinearIcon.byCatalog("playlist"); }
        static get playlist_add(): LinearIcon { return LinearIcon.byCatalog("playlist-add"); }
        static get guitar(): LinearIcon { return LinearIcon.byCatalog("guitar"); }
        static get trumpet(): LinearIcon { return LinearIcon.byCatalog("trumpet"); }
        static get album(): LinearIcon { return LinearIcon.byCatalog("album"); }
        static get shuffle(): LinearIcon { return LinearIcon.byCatalog("shuffle"); }
        static get repeat_one(): LinearIcon { return LinearIcon.byCatalog("repeat-one"); }
        static get repeat(): LinearIcon { return LinearIcon.byCatalog("repeat"); }
        static get headphones(): LinearIcon { return LinearIcon.byCatalog("headphones"); }
        static get headset(): LinearIcon { return LinearIcon.byCatalog("headset"); }
        static get loudspeaker(): LinearIcon { return LinearIcon.byCatalog("loudspeaker"); }
        static get equalizer(): LinearIcon { return LinearIcon.byCatalog("equalizer"); }
        static get theater(): LinearIcon { return LinearIcon.byCatalog("theater"); }
        static get _3d_glasses(): LinearIcon { return LinearIcon.byCatalog("3d-glasses"); }
        static get ticket(): LinearIcon { return LinearIcon.byCatalog("ticket"); }
        static get presentation(): LinearIcon { return LinearIcon.byCatalog("presentation"); }
        static get play(): LinearIcon { return LinearIcon.byCatalog("play"); }
        static get film_play(): LinearIcon { return LinearIcon.byCatalog("film-play"); }
        static get clapboard_play(): LinearIcon { return LinearIcon.byCatalog("clapboard-play"); }
        static get media(): LinearIcon { return LinearIcon.byCatalog("media"); }
        static get film(): LinearIcon { return LinearIcon.byCatalog("film"); }
        static get film2(): LinearIcon { return LinearIcon.byCatalog("film2"); }
        static get surveillance(): LinearIcon { return LinearIcon.byCatalog("surveillance"); }
        static get surveillance2(): LinearIcon { return LinearIcon.byCatalog("surveillance2"); }
        static get camera(): LinearIcon { return LinearIcon.byCatalog("camera"); }
        static get camera_crossed(): LinearIcon { return LinearIcon.byCatalog("camera-crossed"); }
        static get camera_play(): LinearIcon { return LinearIcon.byCatalog("camera-play"); }
        static get time_lapse(): LinearIcon { return LinearIcon.byCatalog("time-lapse"); }
        static get record(): LinearIcon { return LinearIcon.byCatalog("record"); }
        static get camera2(): LinearIcon { return LinearIcon.byCatalog("camera2"); }
        static get camera_flip(): LinearIcon { return LinearIcon.byCatalog("camera-flip"); }
        static get panorama(): LinearIcon { return LinearIcon.byCatalog("panorama"); }
        static get time_lapse2(): LinearIcon { return LinearIcon.byCatalog("time-lapse2"); }
        static get shutter(): LinearIcon { return LinearIcon.byCatalog("shutter"); }
        static get shutter2(): LinearIcon { return LinearIcon.byCatalog("shutter2"); }
        static get face_detection(): LinearIcon { return LinearIcon.byCatalog("face-detection"); }
        static get flare(): LinearIcon { return LinearIcon.byCatalog("flare"); }
        static get convex(): LinearIcon { return LinearIcon.byCatalog("convex"); }
        static get concave(): LinearIcon { return LinearIcon.byCatalog("concave"); }
        static get picture(): LinearIcon { return LinearIcon.byCatalog("picture"); }
        static get picture2(): LinearIcon { return LinearIcon.byCatalog("picture2"); }
        static get picture3(): LinearIcon { return LinearIcon.byCatalog("picture3"); }
        static get pictures(): LinearIcon { return LinearIcon.byCatalog("pictures"); }
        static get book(): LinearIcon { return LinearIcon.byCatalog("book"); }
        static get audio_book(): LinearIcon { return LinearIcon.byCatalog("audio-book"); }
        static get book2(): LinearIcon { return LinearIcon.byCatalog("book2"); }
        static get bookmark(): LinearIcon { return LinearIcon.byCatalog("bookmark"); }
        static get bookmark2(): LinearIcon { return LinearIcon.byCatalog("bookmark2"); }
        static get label(): LinearIcon { return LinearIcon.byCatalog("label"); }
        static get library(): LinearIcon { return LinearIcon.byCatalog("library"); }
        static get library2(): LinearIcon { return LinearIcon.byCatalog("library2"); }
        static get contacts(): LinearIcon { return LinearIcon.byCatalog("contacts"); }
        static get profile(): LinearIcon { return LinearIcon.byCatalog("profile"); }
        static get portrait(): LinearIcon { return LinearIcon.byCatalog("portrait"); }
        static get portrait2(): LinearIcon { return LinearIcon.byCatalog("portrait2"); }
        static get user(): LinearIcon { return LinearIcon.byCatalog("user"); }
        static get user_plus(): LinearIcon { return LinearIcon.byCatalog("user-plus"); }
        static get user_minus(): LinearIcon { return LinearIcon.byCatalog("user-minus"); }
        static get user_lock(): LinearIcon { return LinearIcon.byCatalog("user-lock"); }
        static get users(): LinearIcon { return LinearIcon.byCatalog("users"); }
        static get users2(): LinearIcon { return LinearIcon.byCatalog("users2"); }
        static get users_plus(): LinearIcon { return LinearIcon.byCatalog("users-plus"); }
        static get users_minus(): LinearIcon { return LinearIcon.byCatalog("users-minus"); }
        static get group_work(): LinearIcon { return LinearIcon.byCatalog("group-work"); }
        static get woman(): LinearIcon { return LinearIcon.byCatalog("woman"); }
        static get man(): LinearIcon { return LinearIcon.byCatalog("man"); }
        static get baby(): LinearIcon { return LinearIcon.byCatalog("baby"); }
        static get baby2(): LinearIcon { return LinearIcon.byCatalog("baby2"); }
        static get baby3(): LinearIcon { return LinearIcon.byCatalog("baby3"); }
        static get baby_bottle(): LinearIcon { return LinearIcon.byCatalog("baby-bottle"); }
        static get walk(): LinearIcon { return LinearIcon.byCatalog("walk"); }
        static get hand_waving(): LinearIcon { return LinearIcon.byCatalog("hand-waving"); }
        static get jump(): LinearIcon { return LinearIcon.byCatalog("jump"); }
        static get run(): LinearIcon { return LinearIcon.byCatalog("run"); }
        static get woman2(): LinearIcon { return LinearIcon.byCatalog("woman2"); }
        static get man2(): LinearIcon { return LinearIcon.byCatalog("man2"); }
        static get man_woman(): LinearIcon { return LinearIcon.byCatalog("man-woman"); }
        static get height(): LinearIcon { return LinearIcon.byCatalog("height"); }
        static get weight(): LinearIcon { return LinearIcon.byCatalog("weight"); }
        static get scale(): LinearIcon { return LinearIcon.byCatalog("scale"); }
        static get button(): LinearIcon { return LinearIcon.byCatalog("button"); }
        static get bow_tie(): LinearIcon { return LinearIcon.byCatalog("bow-tie"); }
        static get tie(): LinearIcon { return LinearIcon.byCatalog("tie"); }
        static get socks(): LinearIcon { return LinearIcon.byCatalog("socks"); }
        static get shoe(): LinearIcon { return LinearIcon.byCatalog("shoe"); }
        static get shoes(): LinearIcon { return LinearIcon.byCatalog("shoes"); }
        static get hat(): LinearIcon { return LinearIcon.byCatalog("hat"); }
        static get pants(): LinearIcon { return LinearIcon.byCatalog("pants"); }
        static get shorts(): LinearIcon { return LinearIcon.byCatalog("shorts"); }
        static get flip_flops(): LinearIcon { return LinearIcon.byCatalog("flip-flops"); }
        static get shirt(): LinearIcon { return LinearIcon.byCatalog("shirt"); }
        static get hanger(): LinearIcon { return LinearIcon.byCatalog("hanger"); }
        static get laundry(): LinearIcon { return LinearIcon.byCatalog("laundry"); }
        static get store(): LinearIcon { return LinearIcon.byCatalog("store"); }
        static get haircut(): LinearIcon { return LinearIcon.byCatalog("haircut"); }
        static get store_24(): LinearIcon { return LinearIcon.byCatalog("store-24"); }
        static get barcode(): LinearIcon { return LinearIcon.byCatalog("barcode"); }
        static get barcode2(): LinearIcon { return LinearIcon.byCatalog("barcode2"); }
        static get barcode3(): LinearIcon { return LinearIcon.byCatalog("barcode3"); }
        static get cashier(): LinearIcon { return LinearIcon.byCatalog("cashier"); }
        static get bag(): LinearIcon { return LinearIcon.byCatalog("bag"); }
        static get bag2(): LinearIcon { return LinearIcon.byCatalog("bag2"); }
        static get cart(): LinearIcon { return LinearIcon.byCatalog("cart"); }
        static get cart_empty(): LinearIcon { return LinearIcon.byCatalog("cart-empty"); }
        static get cart_full(): LinearIcon { return LinearIcon.byCatalog("cart-full"); }
        static get cart_plus(): LinearIcon { return LinearIcon.byCatalog("cart-plus"); }
        static get cart_plus2(): LinearIcon { return LinearIcon.byCatalog("cart-plus2"); }
        static get cart_add(): LinearIcon { return LinearIcon.byCatalog("cart-add"); }
        static get cart_remove(): LinearIcon { return LinearIcon.byCatalog("cart-remove"); }
        static get cart_exchange(): LinearIcon { return LinearIcon.byCatalog("cart-exchange"); }
        static get tag(): LinearIcon { return LinearIcon.byCatalog("tag"); }
        static get tags(): LinearIcon { return LinearIcon.byCatalog("tags"); }
        static get receipt(): LinearIcon { return LinearIcon.byCatalog("receipt"); }
        static get wallet(): LinearIcon { return LinearIcon.byCatalog("wallet"); }
        static get credit_card(): LinearIcon { return LinearIcon.byCatalog("credit-card"); }
        static get cash_dollar(): LinearIcon { return LinearIcon.byCatalog("cash-dollar"); }
        static get cash_euro(): LinearIcon { return LinearIcon.byCatalog("cash-euro"); }
        static get cash_pound(): LinearIcon { return LinearIcon.byCatalog("cash-pound"); }
        static get cash_yen(): LinearIcon { return LinearIcon.byCatalog("cash-yen"); }
        static get bag_dollar(): LinearIcon { return LinearIcon.byCatalog("bag-dollar"); }
        static get bag_euro(): LinearIcon { return LinearIcon.byCatalog("bag-euro"); }
        static get bag_pound(): LinearIcon { return LinearIcon.byCatalog("bag-pound"); }
        static get bag_yen(): LinearIcon { return LinearIcon.byCatalog("bag-yen"); }
        static get coin_dollar(): LinearIcon { return LinearIcon.byCatalog("coin-dollar"); }
        static get coin_euro(): LinearIcon { return LinearIcon.byCatalog("coin-euro"); }
        static get coin_pound(): LinearIcon { return LinearIcon.byCatalog("coin-pound"); }
        static get coin_yen(): LinearIcon { return LinearIcon.byCatalog("coin-yen"); }
        static get calculator(): LinearIcon { return LinearIcon.byCatalog("calculator"); }
        static get calculator2(): LinearIcon { return LinearIcon.byCatalog("calculator2"); }
        static get abacus(): LinearIcon { return LinearIcon.byCatalog("abacus"); }
        static get vault(): LinearIcon { return LinearIcon.byCatalog("vault"); }
        static get telephone(): LinearIcon { return LinearIcon.byCatalog("telephone"); }
        static get phone_lock(): LinearIcon { return LinearIcon.byCatalog("phone-lock"); }
        static get phone_wave(): LinearIcon { return LinearIcon.byCatalog("phone-wave"); }
        static get phone_pause(): LinearIcon { return LinearIcon.byCatalog("phone-pause"); }
        static get phone_outgoing(): LinearIcon { return LinearIcon.byCatalog("phone-outgoing"); }
        static get phone_incoming(): LinearIcon { return LinearIcon.byCatalog("phone-incoming"); }
        static get phone_in_out(): LinearIcon { return LinearIcon.byCatalog("phone-in-out"); }
        static get phone_error(): LinearIcon { return LinearIcon.byCatalog("phone-error"); }
        static get phone_sip(): LinearIcon { return LinearIcon.byCatalog("phone-sip"); }
        static get phone_plus(): LinearIcon { return LinearIcon.byCatalog("phone-plus"); }
        static get phone_minus(): LinearIcon { return LinearIcon.byCatalog("phone-minus"); }
        static get voicemail(): LinearIcon { return LinearIcon.byCatalog("voicemail"); }
        static get dial(): LinearIcon { return LinearIcon.byCatalog("dial"); }
        static get telephone2(): LinearIcon { return LinearIcon.byCatalog("telephone2"); }
        static get pushpin(): LinearIcon { return LinearIcon.byCatalog("pushpin"); }
        static get pushpin2(): LinearIcon { return LinearIcon.byCatalog("pushpin2"); }
        static get map_marker(): LinearIcon { return LinearIcon.byCatalog("map-marker"); }
        static get map_marker_user(): LinearIcon { return LinearIcon.byCatalog("map-marker-user"); }
        static get map_marker_down(): LinearIcon { return LinearIcon.byCatalog("map-marker-down"); }
        static get map_marker_check(): LinearIcon { return LinearIcon.byCatalog("map-marker-check"); }
        static get map_marker_crossed(): LinearIcon { return LinearIcon.byCatalog("map-marker-crossed"); }
        static get radar(): LinearIcon { return LinearIcon.byCatalog("radar"); }
        static get compass2(): LinearIcon { return LinearIcon.byCatalog("compass2"); }
        static get map(): LinearIcon { return LinearIcon.byCatalog("map"); }
        static get map2(): LinearIcon { return LinearIcon.byCatalog("map2"); }
        static get location(): LinearIcon { return LinearIcon.byCatalog("location"); }
        static get road_sign(): LinearIcon { return LinearIcon.byCatalog("road-sign"); }
        static get calendar_empty(): LinearIcon { return LinearIcon.byCatalog("calendar-empty"); }
        static get calendar_check(): LinearIcon { return LinearIcon.byCatalog("calendar-check"); }
        static get calendar_cross(): LinearIcon { return LinearIcon.byCatalog("calendar-cross"); }
        static get calendar_31(): LinearIcon { return LinearIcon.byCatalog("calendar-31"); }
        static get calendar_full(): LinearIcon { return LinearIcon.byCatalog("calendar-full"); }
        static get calendar_insert(): LinearIcon { return LinearIcon.byCatalog("calendar-insert"); }
        static get calendar_text(): LinearIcon { return LinearIcon.byCatalog("calendar-text"); }
        static get calendar_user(): LinearIcon { return LinearIcon.byCatalog("calendar-user"); }
        static get mouse(): LinearIcon { return LinearIcon.byCatalog("mouse"); }
        static get mouse_left(): LinearIcon { return LinearIcon.byCatalog("mouse-left"); }
        static get mouse_right(): LinearIcon { return LinearIcon.byCatalog("mouse-right"); }
        static get mouse_both(): LinearIcon { return LinearIcon.byCatalog("mouse-both"); }
        static get keyboard(): LinearIcon { return LinearIcon.byCatalog("keyboard"); }
        static get keyboard_up(): LinearIcon { return LinearIcon.byCatalog("keyboard-up"); }
        static get keyboard_down(): LinearIcon { return LinearIcon.byCatalog("keyboard-down"); }
        static get delete(): LinearIcon { return LinearIcon.byCatalog("delete"); }
        static get spell_check(): LinearIcon { return LinearIcon.byCatalog("spell-check"); }
        static get escape(): LinearIcon { return LinearIcon.byCatalog("escape"); }
        static get enter2(): LinearIcon { return LinearIcon.byCatalog("enter2"); }
        static get screen(): LinearIcon { return LinearIcon.byCatalog("screen"); }
        static get aspect_ratio(): LinearIcon { return LinearIcon.byCatalog("aspect-ratio"); }
        static get signal(): LinearIcon { return LinearIcon.byCatalog("signal"); }
        static get signal_lock(): LinearIcon { return LinearIcon.byCatalog("signal-lock"); }
        static get signal_80(): LinearIcon { return LinearIcon.byCatalog("signal-80"); }
        static get signal_60(): LinearIcon { return LinearIcon.byCatalog("signal-60"); }
        static get signal_40(): LinearIcon { return LinearIcon.byCatalog("signal-40"); }
        static get signal_20(): LinearIcon { return LinearIcon.byCatalog("signal-20"); }
        static get signal_0(): LinearIcon { return LinearIcon.byCatalog("signal-0"); }
        static get signal_blocked(): LinearIcon { return LinearIcon.byCatalog("signal-blocked"); }
        static get sim(): LinearIcon { return LinearIcon.byCatalog("sim"); }
        static get flash_memory(): LinearIcon { return LinearIcon.byCatalog("flash-memory"); }
        static get usb_drive(): LinearIcon { return LinearIcon.byCatalog("usb-drive"); }
        static get phone(): LinearIcon { return LinearIcon.byCatalog("phone"); }
        static get smartphone(): LinearIcon { return LinearIcon.byCatalog("smartphone"); }
        static get smartphone_notification(): LinearIcon { return LinearIcon.byCatalog("smartphone-notification"); }
        static get smartphone_vibration(): LinearIcon { return LinearIcon.byCatalog("smartphone-vibration"); }
        static get smartphone_embed(): LinearIcon { return LinearIcon.byCatalog("smartphone-embed"); }
        static get smartphone_waves(): LinearIcon { return LinearIcon.byCatalog("smartphone-waves"); }
        static get tablet(): LinearIcon { return LinearIcon.byCatalog("tablet"); }
        static get tablet2(): LinearIcon { return LinearIcon.byCatalog("tablet2"); }
        static get laptop(): LinearIcon { return LinearIcon.byCatalog("laptop"); }
        static get laptop_phone(): LinearIcon { return LinearIcon.byCatalog("laptop-phone"); }
        static get desktop(): LinearIcon { return LinearIcon.byCatalog("desktop"); }
        static get launch(): LinearIcon { return LinearIcon.byCatalog("launch"); }
        static get new_tab(): LinearIcon { return LinearIcon.byCatalog("new-tab"); }
        static get window(): LinearIcon { return LinearIcon.byCatalog("window"); }
        static get cable(): LinearIcon { return LinearIcon.byCatalog("cable"); }
        static get cable2(): LinearIcon { return LinearIcon.byCatalog("cable2"); }
        static get tv(): LinearIcon { return LinearIcon.byCatalog("tv"); }
        static get radio(): LinearIcon { return LinearIcon.byCatalog("radio"); }
        static get remote_control(): LinearIcon { return LinearIcon.byCatalog("remote-control"); }
        static get power_switch(): LinearIcon { return LinearIcon.byCatalog("power-switch"); }
        static get power(): LinearIcon { return LinearIcon.byCatalog("power"); }
        static get power_crossed(): LinearIcon { return LinearIcon.byCatalog("power-crossed"); }
        static get flash_auto(): LinearIcon { return LinearIcon.byCatalog("flash-auto"); }
        static get lamp(): LinearIcon { return LinearIcon.byCatalog("lamp"); }
        static get flashlight(): LinearIcon { return LinearIcon.byCatalog("flashlight"); }
        static get lampshade(): LinearIcon { return LinearIcon.byCatalog("lampshade"); }
        static get cord(): LinearIcon { return LinearIcon.byCatalog("cord"); }
        static get outlet(): LinearIcon { return LinearIcon.byCatalog("outlet"); }
        static get battery_power(): LinearIcon { return LinearIcon.byCatalog("battery-power"); }
        static get battery_empty(): LinearIcon { return LinearIcon.byCatalog("battery-empty"); }
        static get battery_alert(): LinearIcon { return LinearIcon.byCatalog("battery-alert"); }
        static get battery_error(): LinearIcon { return LinearIcon.byCatalog("battery-error"); }
        static get battery_low1(): LinearIcon { return LinearIcon.byCatalog("battery-low1"); }
        static get battery_low2(): LinearIcon { return LinearIcon.byCatalog("battery-low2"); }
        static get battery_low3(): LinearIcon { return LinearIcon.byCatalog("battery-low3"); }
        static get battery_mid1(): LinearIcon { return LinearIcon.byCatalog("battery-mid1"); }
        static get battery_mid2(): LinearIcon { return LinearIcon.byCatalog("battery-mid2"); }
        static get battery_mid3(): LinearIcon { return LinearIcon.byCatalog("battery-mid3"); }
        static get battery_full(): LinearIcon { return LinearIcon.byCatalog("battery-full"); }
        static get battery_charging(): LinearIcon { return LinearIcon.byCatalog("battery-charging"); }
        static get battery_charging2(): LinearIcon { return LinearIcon.byCatalog("battery-charging2"); }
        static get battery_charging3(): LinearIcon { return LinearIcon.byCatalog("battery-charging3"); }
        static get battery_charging4(): LinearIcon { return LinearIcon.byCatalog("battery-charging4"); }
        static get battery_charging5(): LinearIcon { return LinearIcon.byCatalog("battery-charging5"); }
        static get battery_charging6(): LinearIcon { return LinearIcon.byCatalog("battery-charging6"); }
        static get battery_charging7(): LinearIcon { return LinearIcon.byCatalog("battery-charging7"); }
        static get chip(): LinearIcon { return LinearIcon.byCatalog("chip"); }
        static get chip_x64(): LinearIcon { return LinearIcon.byCatalog("chip-x64"); }
        static get chip_x86(): LinearIcon { return LinearIcon.byCatalog("chip-x86"); }
        static get bubble(): LinearIcon { return LinearIcon.byCatalog("bubble"); }
        static get bubbles(): LinearIcon { return LinearIcon.byCatalog("bubbles"); }
        static get bubble_dots(): LinearIcon { return LinearIcon.byCatalog("bubble-dots"); }
        static get bubble_alert(): LinearIcon { return LinearIcon.byCatalog("bubble-alert"); }
        static get bubble_question(): LinearIcon { return LinearIcon.byCatalog("bubble-question"); }
        static get bubble_text(): LinearIcon { return LinearIcon.byCatalog("bubble-text"); }
        static get bubble_pencil(): LinearIcon { return LinearIcon.byCatalog("bubble-pencil"); }
        static get bubble_picture(): LinearIcon { return LinearIcon.byCatalog("bubble-picture"); }
        static get bubble_video(): LinearIcon { return LinearIcon.byCatalog("bubble-video"); }
        static get bubble_user(): LinearIcon { return LinearIcon.byCatalog("bubble-user"); }
        static get bubble_quote(): LinearIcon { return LinearIcon.byCatalog("bubble-quote"); }
        static get bubble_heart(): LinearIcon { return LinearIcon.byCatalog("bubble-heart"); }
        static get bubble_emoticon(): LinearIcon { return LinearIcon.byCatalog("bubble-emoticon"); }
        static get bubble_attachment(): LinearIcon { return LinearIcon.byCatalog("bubble-attachment"); }
        static get phone_bubble(): LinearIcon { return LinearIcon.byCatalog("phone-bubble"); }
        static get quote_open(): LinearIcon { return LinearIcon.byCatalog("quote-open"); }
        static get quote_close(): LinearIcon { return LinearIcon.byCatalog("quote-close"); }
        static get dna(): LinearIcon { return LinearIcon.byCatalog("dna"); }
        static get heart_pulse(): LinearIcon { return LinearIcon.byCatalog("heart-pulse"); }
        static get pulse(): LinearIcon { return LinearIcon.byCatalog("pulse"); }
        static get syringe(): LinearIcon { return LinearIcon.byCatalog("syringe"); }
        static get pills(): LinearIcon { return LinearIcon.byCatalog("pills"); }
        static get first_aid(): LinearIcon { return LinearIcon.byCatalog("first-aid"); }
        static get lifebuoy(): LinearIcon { return LinearIcon.byCatalog("lifebuoy"); }
        static get bandage(): LinearIcon { return LinearIcon.byCatalog("bandage"); }
        static get bandages(): LinearIcon { return LinearIcon.byCatalog("bandages"); }
        static get thermometer(): LinearIcon { return LinearIcon.byCatalog("thermometer"); }
        static get microscope(): LinearIcon { return LinearIcon.byCatalog("microscope"); }
        static get brain(): LinearIcon { return LinearIcon.byCatalog("brain"); }
        static get beaker(): LinearIcon { return LinearIcon.byCatalog("beaker"); }
        static get skull(): LinearIcon { return LinearIcon.byCatalog("skull"); }
        static get bone(): LinearIcon { return LinearIcon.byCatalog("bone"); }
        static get construction(): LinearIcon { return LinearIcon.byCatalog("construction"); }
        static get construction_cone(): LinearIcon { return LinearIcon.byCatalog("construction-cone"); }
        static get pie_chart(): LinearIcon { return LinearIcon.byCatalog("pie-chart"); }
        static get pie_chart2(): LinearIcon { return LinearIcon.byCatalog("pie-chart2"); }
        static get graph(): LinearIcon { return LinearIcon.byCatalog("graph"); }
        static get chart_growth(): LinearIcon { return LinearIcon.byCatalog("chart-growth"); }
        static get chart_bars(): LinearIcon { return LinearIcon.byCatalog("chart-bars"); }
        static get chart_settings(): LinearIcon { return LinearIcon.byCatalog("chart-settings"); }
        static get cake(): LinearIcon { return LinearIcon.byCatalog("cake"); }
        static get gift(): LinearIcon { return LinearIcon.byCatalog("gift"); }
        static get balloon(): LinearIcon { return LinearIcon.byCatalog("balloon"); }
        static get rank(): LinearIcon { return LinearIcon.byCatalog("rank"); }
        static get rank2(): LinearIcon { return LinearIcon.byCatalog("rank2"); }
        static get rank3(): LinearIcon { return LinearIcon.byCatalog("rank3"); }
        static get crown(): LinearIcon { return LinearIcon.byCatalog("crown"); }
        static get lotus(): LinearIcon { return LinearIcon.byCatalog("lotus"); }
        static get diamond(): LinearIcon { return LinearIcon.byCatalog("diamond"); }
        static get diamond2(): LinearIcon { return LinearIcon.byCatalog("diamond2"); }
        static get diamond3(): LinearIcon { return LinearIcon.byCatalog("diamond3"); }
        static get diamond4(): LinearIcon { return LinearIcon.byCatalog("diamond4"); }
        static get linearicons(): LinearIcon { return LinearIcon.byCatalog("linearicons"); }
        static get teacup(): LinearIcon { return LinearIcon.byCatalog("teacup"); }
        static get teapot(): LinearIcon { return LinearIcon.byCatalog("teapot"); }
        static get glass(): LinearIcon { return LinearIcon.byCatalog("glass"); }
        static get bottle2(): LinearIcon { return LinearIcon.byCatalog("bottle2"); }
        static get glass_cocktail(): LinearIcon { return LinearIcon.byCatalog("glass-cocktail"); }
        static get glass2(): LinearIcon { return LinearIcon.byCatalog("glass2"); }
        static get dinner(): LinearIcon { return LinearIcon.byCatalog("dinner"); }
        static get dinner2(): LinearIcon { return LinearIcon.byCatalog("dinner2"); }
        static get chef(): LinearIcon { return LinearIcon.byCatalog("chef"); }
        static get scale2(): LinearIcon { return LinearIcon.byCatalog("scale2"); }
        static get egg(): LinearIcon { return LinearIcon.byCatalog("egg"); }
        static get egg2(): LinearIcon { return LinearIcon.byCatalog("egg2"); }
        static get eggs(): LinearIcon { return LinearIcon.byCatalog("eggs"); }
        static get platter(): LinearIcon { return LinearIcon.byCatalog("platter"); }
        static get steak(): LinearIcon { return LinearIcon.byCatalog("steak"); }
        static get hamburger(): LinearIcon { return LinearIcon.byCatalog("hamburger"); }
        static get hotdog(): LinearIcon { return LinearIcon.byCatalog("hotdog"); }
        static get pizza(): LinearIcon { return LinearIcon.byCatalog("pizza"); }
        static get sausage(): LinearIcon { return LinearIcon.byCatalog("sausage"); }
        static get chicken(): LinearIcon { return LinearIcon.byCatalog("chicken"); }
        static get fish(): LinearIcon { return LinearIcon.byCatalog("fish"); }
        static get carrot(): LinearIcon { return LinearIcon.byCatalog("carrot"); }
        static get cheese(): LinearIcon { return LinearIcon.byCatalog("cheese"); }
        static get bread(): LinearIcon { return LinearIcon.byCatalog("bread"); }
        static get ice_cream(): LinearIcon { return LinearIcon.byCatalog("ice-cream"); }
        static get ice_cream2(): LinearIcon { return LinearIcon.byCatalog("ice-cream2"); }
        static get candy(): LinearIcon { return LinearIcon.byCatalog("candy"); }
        static get lollipop(): LinearIcon { return LinearIcon.byCatalog("lollipop"); }
        static get coffee_bean(): LinearIcon { return LinearIcon.byCatalog("coffee-bean"); }
        static get coffee_cup(): LinearIcon { return LinearIcon.byCatalog("coffee-cup"); }
        static get cherry(): LinearIcon { return LinearIcon.byCatalog("cherry"); }
        static get grapes(): LinearIcon { return LinearIcon.byCatalog("grapes"); }
        static get citrus(): LinearIcon { return LinearIcon.byCatalog("citrus"); }
        static get apple(): LinearIcon { return LinearIcon.byCatalog("apple"); }
        static get leaf(): LinearIcon { return LinearIcon.byCatalog("leaf"); }
        static get landscape(): LinearIcon { return LinearIcon.byCatalog("landscape"); }
        static get pine_tree(): LinearIcon { return LinearIcon.byCatalog("pine-tree"); }
        static get tree(): LinearIcon { return LinearIcon.byCatalog("tree"); }
        static get cactus(): LinearIcon { return LinearIcon.byCatalog("cactus"); }
        static get paw(): LinearIcon { return LinearIcon.byCatalog("paw"); }
        static get footprint(): LinearIcon { return LinearIcon.byCatalog("footprint"); }
        static get speed_slow(): LinearIcon { return LinearIcon.byCatalog("speed-slow"); }
        static get speed_medium(): LinearIcon { return LinearIcon.byCatalog("speed-medium"); }
        static get speed_fast(): LinearIcon { return LinearIcon.byCatalog("speed-fast"); }
        static get rocket(): LinearIcon { return LinearIcon.byCatalog("rocket"); }
        static get hammer2(): LinearIcon { return LinearIcon.byCatalog("hammer2"); }
        static get balance(): LinearIcon { return LinearIcon.byCatalog("balance"); }
        static get briefcase(): LinearIcon { return LinearIcon.byCatalog("briefcase"); }
        static get luggage_weight(): LinearIcon { return LinearIcon.byCatalog("luggage-weight"); }
        static get dolly(): LinearIcon { return LinearIcon.byCatalog("dolly"); }
        static get plane(): LinearIcon { return LinearIcon.byCatalog("plane"); }
        static get plane_crossed(): LinearIcon { return LinearIcon.byCatalog("plane-crossed"); }
        static get helicopter(): LinearIcon { return LinearIcon.byCatalog("helicopter"); }
        static get traffic_lights(): LinearIcon { return LinearIcon.byCatalog("traffic-lights"); }
        static get siren(): LinearIcon { return LinearIcon.byCatalog("siren"); }
        static get road(): LinearIcon { return LinearIcon.byCatalog("road"); }
        static get engine(): LinearIcon { return LinearIcon.byCatalog("engine"); }
        static get oil_pressure(): LinearIcon { return LinearIcon.byCatalog("oil-pressure"); }
        static get coolant_temperature(): LinearIcon { return LinearIcon.byCatalog("coolant-temperature"); }
        static get car_battery(): LinearIcon { return LinearIcon.byCatalog("car-battery"); }
        static get gas(): LinearIcon { return LinearIcon.byCatalog("gas"); }
        static get gallon(): LinearIcon { return LinearIcon.byCatalog("gallon"); }
        static get transmission(): LinearIcon { return LinearIcon.byCatalog("transmission"); }
        static get car(): LinearIcon { return LinearIcon.byCatalog("car"); }
        static get car_wash(): LinearIcon { return LinearIcon.byCatalog("car-wash"); }
        static get car_wash2(): LinearIcon { return LinearIcon.byCatalog("car-wash2"); }
        static get bus(): LinearIcon { return LinearIcon.byCatalog("bus"); }
        static get bus2(): LinearIcon { return LinearIcon.byCatalog("bus2"); }
        static get car2(): LinearIcon { return LinearIcon.byCatalog("car2"); }
        static get parking(): LinearIcon { return LinearIcon.byCatalog("parking"); }
        static get car_lock(): LinearIcon { return LinearIcon.byCatalog("car-lock"); }
        static get taxi(): LinearIcon { return LinearIcon.byCatalog("taxi"); }
        static get car_siren(): LinearIcon { return LinearIcon.byCatalog("car-siren"); }
        static get car_wash3(): LinearIcon { return LinearIcon.byCatalog("car-wash3"); }
        static get car_wash4(): LinearIcon { return LinearIcon.byCatalog("car-wash4"); }
        static get ambulance(): LinearIcon { return LinearIcon.byCatalog("ambulance"); }
        static get truck(): LinearIcon { return LinearIcon.byCatalog("truck"); }
        static get trailer(): LinearIcon { return LinearIcon.byCatalog("trailer"); }
        static get scale_truck(): LinearIcon { return LinearIcon.byCatalog("scale-truck"); }
        static get train(): LinearIcon { return LinearIcon.byCatalog("train"); }
        static get ship(): LinearIcon { return LinearIcon.byCatalog("ship"); }
        static get ship2(): LinearIcon { return LinearIcon.byCatalog("ship2"); }
        static get anchor(): LinearIcon { return LinearIcon.byCatalog("anchor"); }
        static get boat(): LinearIcon { return LinearIcon.byCatalog("boat"); }
        static get bicycle(): LinearIcon { return LinearIcon.byCatalog("bicycle"); }
        static get bicycle2(): LinearIcon { return LinearIcon.byCatalog("bicycle2"); }
        static get dumbbell(): LinearIcon { return LinearIcon.byCatalog("dumbbell"); }
        static get bench_press(): LinearIcon { return LinearIcon.byCatalog("bench-press"); }
        static get swim(): LinearIcon { return LinearIcon.byCatalog("swim"); }
        static get football(): LinearIcon { return LinearIcon.byCatalog("football"); }
        static get baseball_bat(): LinearIcon { return LinearIcon.byCatalog("baseball-bat"); }
        static get baseball(): LinearIcon { return LinearIcon.byCatalog("baseball"); }
        static get tennis(): LinearIcon { return LinearIcon.byCatalog("tennis"); }
        static get tennis2(): LinearIcon { return LinearIcon.byCatalog("tennis2"); }
        static get ping_pong(): LinearIcon { return LinearIcon.byCatalog("ping-pong"); }
        static get hockey(): LinearIcon { return LinearIcon.byCatalog("hockey"); }
        static get _8ball(): LinearIcon { return LinearIcon.byCatalog("8ball"); }
        static get bowling(): LinearIcon { return LinearIcon.byCatalog("bowling"); }
        static get bowling_pins(): LinearIcon { return LinearIcon.byCatalog("bowling-pins"); }
        static get golf(): LinearIcon { return LinearIcon.byCatalog("golf"); }
        static get golf2(): LinearIcon { return LinearIcon.byCatalog("golf2"); }
        static get archery(): LinearIcon { return LinearIcon.byCatalog("archery"); }
        static get slingshot(): LinearIcon { return LinearIcon.byCatalog("slingshot"); }
        static get soccer(): LinearIcon { return LinearIcon.byCatalog("soccer"); }
        static get basketball(): LinearIcon { return LinearIcon.byCatalog("basketball"); }
        static get cube(): LinearIcon { return LinearIcon.byCatalog("cube"); }
        static get _3d_rotate(): LinearIcon { return LinearIcon.byCatalog("3d-rotate"); }
        static get puzzle(): LinearIcon { return LinearIcon.byCatalog("puzzle"); }
        static get glasses(): LinearIcon { return LinearIcon.byCatalog("glasses"); }
        static get glasses2(): LinearIcon { return LinearIcon.byCatalog("glasses2"); }
        static get accessibility(): LinearIcon { return LinearIcon.byCatalog("accessibility"); }
        static get wheelchair(): LinearIcon { return LinearIcon.byCatalog("wheelchair"); }
        static get wall(): LinearIcon { return LinearIcon.byCatalog("wall"); }
        static get fence(): LinearIcon { return LinearIcon.byCatalog("fence"); }
        static get wall2(): LinearIcon { return LinearIcon.byCatalog("wall2"); }
        static get icons(): LinearIcon { return LinearIcon.byCatalog("icons"); }
        static get resize_handle(): LinearIcon { return LinearIcon.byCatalog("resize-handle"); }
        static get icons2(): LinearIcon { return LinearIcon.byCatalog("icons2"); }
        static get select(): LinearIcon { return LinearIcon.byCatalog("select"); }
        static get select2(): LinearIcon { return LinearIcon.byCatalog("select2"); }
        static get site_map(): LinearIcon { return LinearIcon.byCatalog("site-map"); }
        static get earth(): LinearIcon { return LinearIcon.byCatalog("earth"); }
        static get earth_lock(): LinearIcon { return LinearIcon.byCatalog("earth-lock"); }
        static get network(): LinearIcon { return LinearIcon.byCatalog("network"); }
        static get network_lock(): LinearIcon { return LinearIcon.byCatalog("network-lock"); }
        static get planet(): LinearIcon { return LinearIcon.byCatalog("planet"); }
        static get happy(): LinearIcon { return LinearIcon.byCatalog("happy"); }
        static get smile(): LinearIcon { return LinearIcon.byCatalog("smile"); }
        static get grin(): LinearIcon { return LinearIcon.byCatalog("grin"); }
        static get tongue(): LinearIcon { return LinearIcon.byCatalog("tongue"); }
        static get sad(): LinearIcon { return LinearIcon.byCatalog("sad"); }
        static get wink(): LinearIcon { return LinearIcon.byCatalog("wink"); }
        static get dream(): LinearIcon { return LinearIcon.byCatalog("dream"); }
        static get shocked(): LinearIcon { return LinearIcon.byCatalog("shocked"); }
        static get shocked2(): LinearIcon { return LinearIcon.byCatalog("shocked2"); }
        static get tongue2(): LinearIcon { return LinearIcon.byCatalog("tongue2"); }
        static get neutral(): LinearIcon { return LinearIcon.byCatalog("neutral"); }
        static get happy_grin(): LinearIcon { return LinearIcon.byCatalog("happy-grin"); }
        static get cool(): LinearIcon { return LinearIcon.byCatalog("cool"); }
        static get mad(): LinearIcon { return LinearIcon.byCatalog("mad"); }
        static get grin_evil(): LinearIcon { return LinearIcon.byCatalog("grin-evil"); }
        static get evil(): LinearIcon { return LinearIcon.byCatalog("evil"); }
        static get wow(): LinearIcon { return LinearIcon.byCatalog("wow"); }
        static get annoyed(): LinearIcon { return LinearIcon.byCatalog("annoyed"); }
        static get wondering(): LinearIcon { return LinearIcon.byCatalog("wondering"); }
        static get confused(): LinearIcon { return LinearIcon.byCatalog("confused"); }
        static get zipped(): LinearIcon { return LinearIcon.byCatalog("zipped"); }
        static get grumpy(): LinearIcon { return LinearIcon.byCatalog("grumpy"); }
        static get mustache(): LinearIcon { return LinearIcon.byCatalog("mustache"); }
        static get tombstone_hipster(): LinearIcon { return LinearIcon.byCatalog("tombstone-hipster"); }
        static get tombstone(): LinearIcon { return LinearIcon.byCatalog("tombstone"); }
        static get ghost(): LinearIcon { return LinearIcon.byCatalog("ghost"); }
        static get ghost_hipster(): LinearIcon { return LinearIcon.byCatalog("ghost-hipster"); }
        static get halloween(): LinearIcon { return LinearIcon.byCatalog("halloween"); }
        static get christmas(): LinearIcon { return LinearIcon.byCatalog("christmas"); }
        static get easter_egg(): LinearIcon { return LinearIcon.byCatalog("easter-egg"); }
        static get mustache2(): LinearIcon { return LinearIcon.byCatalog("mustache2"); }
        static get mustache_glasses(): LinearIcon { return LinearIcon.byCatalog("mustache-glasses"); }
        static get pipe(): LinearIcon { return LinearIcon.byCatalog("pipe"); }
        static get alarm(): LinearIcon { return LinearIcon.byCatalog("alarm"); }
        static get alarm_add(): LinearIcon { return LinearIcon.byCatalog("alarm-add"); }
        static get alarm_snooze(): LinearIcon { return LinearIcon.byCatalog("alarm-snooze"); }
        static get alarm_ringing(): LinearIcon { return LinearIcon.byCatalog("alarm-ringing"); }
        static get bullhorn(): LinearIcon { return LinearIcon.byCatalog("bullhorn"); }
        static get hearing(): LinearIcon { return LinearIcon.byCatalog("hearing"); }
        static get volume_high(): LinearIcon { return LinearIcon.byCatalog("volume-high"); }
        static get volume_medium(): LinearIcon { return LinearIcon.byCatalog("volume-medium"); }
        static get volume_low(): LinearIcon { return LinearIcon.byCatalog("volume-low"); }
        static get volume(): LinearIcon { return LinearIcon.byCatalog("volume"); }
        static get mute(): LinearIcon { return LinearIcon.byCatalog("mute"); }
        static get lan(): LinearIcon { return LinearIcon.byCatalog("lan"); }
        static get lan2(): LinearIcon { return LinearIcon.byCatalog("lan2"); }
        static get wifi(): LinearIcon { return LinearIcon.byCatalog("wifi"); }
        static get wifi_lock(): LinearIcon { return LinearIcon.byCatalog("wifi-lock"); }
        static get wifi_blocked(): LinearIcon { return LinearIcon.byCatalog("wifi-blocked"); }
        static get wifi_mid(): LinearIcon { return LinearIcon.byCatalog("wifi-mid"); }
        static get wifi_low(): LinearIcon { return LinearIcon.byCatalog("wifi-low"); }
        static get wifi_low2(): LinearIcon { return LinearIcon.byCatalog("wifi-low2"); }
        static get wifi_alert(): LinearIcon { return LinearIcon.byCatalog("wifi-alert"); }
        static get wifi_alert_mid(): LinearIcon { return LinearIcon.byCatalog("wifi-alert-mid"); }
        static get wifi_alert_low(): LinearIcon { return LinearIcon.byCatalog("wifi-alert-low"); }
        static get wifi_alert_low2(): LinearIcon { return LinearIcon.byCatalog("wifi-alert-low2"); }
        static get stream(): LinearIcon { return LinearIcon.byCatalog("stream"); }
        static get stream_check(): LinearIcon { return LinearIcon.byCatalog("stream-check"); }
        static get stream_error(): LinearIcon { return LinearIcon.byCatalog("stream-error"); }
        static get stream_alert(): LinearIcon { return LinearIcon.byCatalog("stream-alert"); }
        static get communication(): LinearIcon { return LinearIcon.byCatalog("communication"); }
        static get communication_crossed(): LinearIcon { return LinearIcon.byCatalog("communication-crossed"); }
        static get broadcast(): LinearIcon { return LinearIcon.byCatalog("broadcast"); }
        static get antenna(): LinearIcon { return LinearIcon.byCatalog("antenna"); }
        static get satellite(): LinearIcon { return LinearIcon.byCatalog("satellite"); }
        static get satellite2(): LinearIcon { return LinearIcon.byCatalog("satellite2"); }
        static get mic(): LinearIcon { return LinearIcon.byCatalog("mic"); }
        static get mic_mute(): LinearIcon { return LinearIcon.byCatalog("mic-mute"); }
        static get mic2(): LinearIcon { return LinearIcon.byCatalog("mic2"); }
        static get spotlights(): LinearIcon { return LinearIcon.byCatalog("spotlights"); }
        static get hourglass(): LinearIcon { return LinearIcon.byCatalog("hourglass"); }
        static get loading(): LinearIcon { return LinearIcon.byCatalog("loading"); }
        static get loading2(): LinearIcon { return LinearIcon.byCatalog("loading2"); }
        static get loading3(): LinearIcon { return LinearIcon.byCatalog("loading3"); }
        static get refresh(): LinearIcon { return LinearIcon.byCatalog("refresh"); }
        static get refresh2(): LinearIcon { return LinearIcon.byCatalog("refresh2"); }
        static get undo(): LinearIcon { return LinearIcon.byCatalog("undo"); }
        static get redo(): LinearIcon { return LinearIcon.byCatalog("redo"); }
        static get jump2(): LinearIcon { return LinearIcon.byCatalog("jump2"); }
        static get undo2(): LinearIcon { return LinearIcon.byCatalog("undo2"); }
        static get redo2(): LinearIcon { return LinearIcon.byCatalog("redo2"); }
        static get sync(): LinearIcon { return LinearIcon.byCatalog("sync"); }
        static get repeat_one2(): LinearIcon { return LinearIcon.byCatalog("repeat-one2"); }
        static get sync_crossed(): LinearIcon { return LinearIcon.byCatalog("sync-crossed"); }
        static get sync2(): LinearIcon { return LinearIcon.byCatalog("sync2"); }
        static get repeat_one3(): LinearIcon { return LinearIcon.byCatalog("repeat-one3"); }
        static get sync_crossed2(): LinearIcon { return LinearIcon.byCatalog("sync-crossed2"); }
        static get return(): LinearIcon { return LinearIcon.byCatalog("return"); }
        static get return2(): LinearIcon { return LinearIcon.byCatalog("return2"); }
        static get refund(): LinearIcon { return LinearIcon.byCatalog("refund"); }
        static get history(): LinearIcon { return LinearIcon.byCatalog("history"); }
        static get history2(): LinearIcon { return LinearIcon.byCatalog("history2"); }
        static get self_timer(): LinearIcon { return LinearIcon.byCatalog("self-timer"); }
        static get clock(): LinearIcon { return LinearIcon.byCatalog("clock"); }
        static get clock2(): LinearIcon { return LinearIcon.byCatalog("clock2"); }
        static get clock3(): LinearIcon { return LinearIcon.byCatalog("clock3"); }
        static get watch(): LinearIcon { return LinearIcon.byCatalog("watch"); }
        static get alarm2(): LinearIcon { return LinearIcon.byCatalog("alarm2"); }
        static get alarm_add2(): LinearIcon { return LinearIcon.byCatalog("alarm-add2"); }
        static get alarm_remove(): LinearIcon { return LinearIcon.byCatalog("alarm-remove"); }
        static get alarm_check(): LinearIcon { return LinearIcon.byCatalog("alarm-check"); }
        static get alarm_error(): LinearIcon { return LinearIcon.byCatalog("alarm-error"); }
        static get timer(): LinearIcon { return LinearIcon.byCatalog("timer"); }
        static get timer_crossed(): LinearIcon { return LinearIcon.byCatalog("timer-crossed"); }
        static get timer2(): LinearIcon { return LinearIcon.byCatalog("timer2"); }
        static get timer_crossed2(): LinearIcon { return LinearIcon.byCatalog("timer-crossed2"); }
        static get download(): LinearIcon { return LinearIcon.byCatalog("download"); }
        static get upload(): LinearIcon { return LinearIcon.byCatalog("upload"); }
        static get download2(): LinearIcon { return LinearIcon.byCatalog("download2"); }
        static get upload2(): LinearIcon { return LinearIcon.byCatalog("upload2"); }
        static get enter_up(): LinearIcon { return LinearIcon.byCatalog("enter-up"); }
        static get enter_down(): LinearIcon { return LinearIcon.byCatalog("enter-down"); }
        static get enter_left(): LinearIcon { return LinearIcon.byCatalog("enter-left"); }
        static get enter_right(): LinearIcon { return LinearIcon.byCatalog("enter-right"); }
        static get exit_up(): LinearIcon { return LinearIcon.byCatalog("exit-up"); }
        static get exit_down(): LinearIcon { return LinearIcon.byCatalog("exit-down"); }
        static get exit_left(): LinearIcon { return LinearIcon.byCatalog("exit-left"); }
        static get exit_right(): LinearIcon { return LinearIcon.byCatalog("exit-right"); }
        static get enter_up2(): LinearIcon { return LinearIcon.byCatalog("enter-up2"); }
        static get enter_down2(): LinearIcon { return LinearIcon.byCatalog("enter-down2"); }
        static get enter_vertical(): LinearIcon { return LinearIcon.byCatalog("enter-vertical"); }
        static get enter_left2(): LinearIcon { return LinearIcon.byCatalog("enter-left2"); }
        static get enter_right2(): LinearIcon { return LinearIcon.byCatalog("enter-right2"); }
        static get enter_horizontal(): LinearIcon { return LinearIcon.byCatalog("enter-horizontal"); }
        static get exit_up2(): LinearIcon { return LinearIcon.byCatalog("exit-up2"); }
        static get exit_down2(): LinearIcon { return LinearIcon.byCatalog("exit-down2"); }
        static get exit_left2(): LinearIcon { return LinearIcon.byCatalog("exit-left2"); }
        static get exit_right2(): LinearIcon { return LinearIcon.byCatalog("exit-right2"); }
        static get cli(): LinearIcon { return LinearIcon.byCatalog("cli"); }
        static get bug(): LinearIcon { return LinearIcon.byCatalog("bug"); }
        static get code(): LinearIcon { return LinearIcon.byCatalog("code"); }
        static get file_code(): LinearIcon { return LinearIcon.byCatalog("file-code"); }
        static get file_image(): LinearIcon { return LinearIcon.byCatalog("file-image"); }
        static get file_zip(): LinearIcon { return LinearIcon.byCatalog("file-zip"); }
        static get file_audio(): LinearIcon { return LinearIcon.byCatalog("file-audio"); }
        static get file_video(): LinearIcon { return LinearIcon.byCatalog("file-video"); }
        static get file_preview(): LinearIcon { return LinearIcon.byCatalog("file-preview"); }
        static get file_charts(): LinearIcon { return LinearIcon.byCatalog("file-charts"); }
        static get file_stats(): LinearIcon { return LinearIcon.byCatalog("file-stats"); }
        static get file_spreadsheet(): LinearIcon { return LinearIcon.byCatalog("file-spreadsheet"); }
        static get link(): LinearIcon { return LinearIcon.byCatalog("link"); }
        static get unlink(): LinearIcon { return LinearIcon.byCatalog("unlink"); }
        static get link2(): LinearIcon { return LinearIcon.byCatalog("link2"); }
        static get unlink2(): LinearIcon { return LinearIcon.byCatalog("unlink2"); }
        static get thumbs_up(): LinearIcon { return LinearIcon.byCatalog("thumbs-up"); }
        static get thumbs_down(): LinearIcon { return LinearIcon.byCatalog("thumbs-down"); }
        static get thumbs_up2(): LinearIcon { return LinearIcon.byCatalog("thumbs-up2"); }
        static get thumbs_down2(): LinearIcon { return LinearIcon.byCatalog("thumbs-down2"); }
        static get thumbs_up3(): LinearIcon { return LinearIcon.byCatalog("thumbs-up3"); }
        static get thumbs_down3(): LinearIcon { return LinearIcon.byCatalog("thumbs-down3"); }
        static get share(): LinearIcon { return LinearIcon.byCatalog("share"); }
        static get share2(): LinearIcon { return LinearIcon.byCatalog("share2"); }
        static get share3(): LinearIcon { return LinearIcon.byCatalog("share3"); }
        static get magnifier(): LinearIcon { return LinearIcon.byCatalog("magnifier"); }
        static get file_search(): LinearIcon { return LinearIcon.byCatalog("file-search"); }
        static get find_replace(): LinearIcon { return LinearIcon.byCatalog("find-replace"); }
        static get zoom_in(): LinearIcon { return LinearIcon.byCatalog("zoom-in"); }
        static get zoom_out(): LinearIcon { return LinearIcon.byCatalog("zoom-out"); }
        static get loupe(): LinearIcon { return LinearIcon.byCatalog("loupe"); }
        static get loupe_zoom_in(): LinearIcon { return LinearIcon.byCatalog("loupe-zoom-in"); }
        static get loupe_zoom_out(): LinearIcon { return LinearIcon.byCatalog("loupe-zoom-out"); }
        static get cross(): LinearIcon { return LinearIcon.byCatalog("cross"); }
        static get menu(): LinearIcon { return LinearIcon.byCatalog("menu"); }
        static get list(): LinearIcon { return LinearIcon.byCatalog("list"); }
        static get list2(): LinearIcon { return LinearIcon.byCatalog("list2"); }
        static get list3(): LinearIcon { return LinearIcon.byCatalog("list3"); }
        static get menu2(): LinearIcon { return LinearIcon.byCatalog("menu2"); }
        static get list4(): LinearIcon { return LinearIcon.byCatalog("list4"); }
        static get menu3(): LinearIcon { return LinearIcon.byCatalog("menu3"); }
        static get exclamation(): LinearIcon { return LinearIcon.byCatalog("exclamation"); }
        static get question(): LinearIcon { return LinearIcon.byCatalog("question"); }
        static get check(): LinearIcon { return LinearIcon.byCatalog("check"); }
        static get cross2(): LinearIcon { return LinearIcon.byCatalog("cross2"); }
        static get plus(): LinearIcon { return LinearIcon.byCatalog("plus"); }
        static get minus(): LinearIcon { return LinearIcon.byCatalog("minus"); }
        static get percent(): LinearIcon { return LinearIcon.byCatalog("percent"); }
        static get chevron_up(): LinearIcon { return LinearIcon.byCatalog("chevron-up"); }
        static get chevron_down(): LinearIcon { return LinearIcon.byCatalog("chevron-down"); }
        static get chevron_left(): LinearIcon { return LinearIcon.byCatalog("chevron-left"); }
        static get chevron_right(): LinearIcon { return LinearIcon.byCatalog("chevron-right"); }
        static get chevrons_expand_vertical(): LinearIcon { return LinearIcon.byCatalog("chevrons-expand-vertical"); }
        static get chevrons_expand_horizontal(): LinearIcon { return LinearIcon.byCatalog("chevrons-expand-horizontal"); }
        static get chevrons_contract_vertical(): LinearIcon { return LinearIcon.byCatalog("chevrons-contract-vertical"); }
        static get chevrons_contract_horizontal(): LinearIcon { return LinearIcon.byCatalog("chevrons-contract-horizontal"); }
        static get arrow_up(): LinearIcon { return LinearIcon.byCatalog("arrow-up"); }
        static get arrow_down(): LinearIcon { return LinearIcon.byCatalog("arrow-down"); }
        static get arrow_left(): LinearIcon { return LinearIcon.byCatalog("arrow-left"); }
        static get arrow_right(): LinearIcon { return LinearIcon.byCatalog("arrow-right"); }
        static get arrow_up_right(): LinearIcon { return LinearIcon.byCatalog("arrow-up-right"); }
        static get arrows_merge(): LinearIcon { return LinearIcon.byCatalog("arrows-merge"); }
        static get arrows_split(): LinearIcon { return LinearIcon.byCatalog("arrows-split"); }
        static get arrow_divert(): LinearIcon { return LinearIcon.byCatalog("arrow-divert"); }
        static get arrow_return(): LinearIcon { return LinearIcon.byCatalog("arrow-return"); }
        static get expand(): LinearIcon { return LinearIcon.byCatalog("expand"); }
        static get contract(): LinearIcon { return LinearIcon.byCatalog("contract"); }
        static get expand2(): LinearIcon { return LinearIcon.byCatalog("expand2"); }
        static get contract2(): LinearIcon { return LinearIcon.byCatalog("contract2"); }
        static get move(): LinearIcon { return LinearIcon.byCatalog("move"); }
        static get tab(): LinearIcon { return LinearIcon.byCatalog("tab"); }
        static get arrow_wave(): LinearIcon { return LinearIcon.byCatalog("arrow-wave"); }
        static get expand3(): LinearIcon { return LinearIcon.byCatalog("expand3"); }
        static get expand4(): LinearIcon { return LinearIcon.byCatalog("expand4"); }
        static get contract3(): LinearIcon { return LinearIcon.byCatalog("contract3"); }
        static get notification(): LinearIcon { return LinearIcon.byCatalog("notification"); }
        static get warning(): LinearIcon { return LinearIcon.byCatalog("warning"); }
        static get notification_circle(): LinearIcon { return LinearIcon.byCatalog("notification-circle"); }
        static get question_circle(): LinearIcon { return LinearIcon.byCatalog("question-circle"); }
        static get menu_circle(): LinearIcon { return LinearIcon.byCatalog("menu-circle"); }
        static get checkmark_circle(): LinearIcon { return LinearIcon.byCatalog("checkmark-circle"); }
        static get cross_circle(): LinearIcon { return LinearIcon.byCatalog("cross-circle"); }
        static get plus_circle(): LinearIcon { return LinearIcon.byCatalog("plus-circle"); }
        static get circle_minus(): LinearIcon { return LinearIcon.byCatalog("circle-minus"); }
        static get percent_circle(): LinearIcon { return LinearIcon.byCatalog("percent-circle"); }
        static get arrow_up_circle(): LinearIcon { return LinearIcon.byCatalog("arrow-up-circle"); }
        static get arrow_down_circle(): LinearIcon { return LinearIcon.byCatalog("arrow-down-circle"); }
        static get arrow_left_circle(): LinearIcon { return LinearIcon.byCatalog("arrow-left-circle"); }
        static get arrow_right_circle(): LinearIcon { return LinearIcon.byCatalog("arrow-right-circle"); }
        static get chevron_up_circle(): LinearIcon { return LinearIcon.byCatalog("chevron-up-circle"); }
        static get chevron_down_circle(): LinearIcon { return LinearIcon.byCatalog("chevron-down-circle"); }
        static get chevron_left_circle(): LinearIcon { return LinearIcon.byCatalog("chevron-left-circle"); }
        static get chevron_right_circle(): LinearIcon { return LinearIcon.byCatalog("chevron-right-circle"); }
        static get backward_circle(): LinearIcon { return LinearIcon.byCatalog("backward-circle"); }
        static get first_circle(): LinearIcon { return LinearIcon.byCatalog("first-circle"); }
        static get previous_circle(): LinearIcon { return LinearIcon.byCatalog("previous-circle"); }
        static get stop_circle(): LinearIcon { return LinearIcon.byCatalog("stop-circle"); }
        static get play_circle(): LinearIcon { return LinearIcon.byCatalog("play-circle"); }
        static get pause_circle(): LinearIcon { return LinearIcon.byCatalog("pause-circle"); }
        static get next_circle(): LinearIcon { return LinearIcon.byCatalog("next-circle"); }
        static get last_circle(): LinearIcon { return LinearIcon.byCatalog("last-circle"); }
        static get forward_circle(): LinearIcon { return LinearIcon.byCatalog("forward-circle"); }
        static get eject_circle(): LinearIcon { return LinearIcon.byCatalog("eject-circle"); }
        static get crop(): LinearIcon { return LinearIcon.byCatalog("crop"); }
        static get frame_expand(): LinearIcon { return LinearIcon.byCatalog("frame-expand"); }
        static get frame_contract(): LinearIcon { return LinearIcon.byCatalog("frame-contract"); }
        static get focus(): LinearIcon { return LinearIcon.byCatalog("focus"); }
        static get transform(): LinearIcon { return LinearIcon.byCatalog("transform"); }
        static get grid(): LinearIcon { return LinearIcon.byCatalog("grid"); }
        static get grid_crossed(): LinearIcon { return LinearIcon.byCatalog("grid-crossed"); }
        static get layers(): LinearIcon { return LinearIcon.byCatalog("layers"); }
        static get layers_crossed(): LinearIcon { return LinearIcon.byCatalog("layers-crossed"); }
        static get toggle(): LinearIcon { return LinearIcon.byCatalog("toggle"); }
        static get rulers(): LinearIcon { return LinearIcon.byCatalog("rulers"); }
        static get ruler(): LinearIcon { return LinearIcon.byCatalog("ruler"); }
        static get funnel(): LinearIcon { return LinearIcon.byCatalog("funnel"); }
        static get flip_horizontal(): LinearIcon { return LinearIcon.byCatalog("flip-horizontal"); }
        static get flip_vertical(): LinearIcon { return LinearIcon.byCatalog("flip-vertical"); }
        static get flip_horizontal2(): LinearIcon { return LinearIcon.byCatalog("flip-horizontal2"); }
        static get flip_vertical2(): LinearIcon { return LinearIcon.byCatalog("flip-vertical2"); }
        static get angle(): LinearIcon { return LinearIcon.byCatalog("angle"); }
        static get angle2(): LinearIcon { return LinearIcon.byCatalog("angle2"); }
        static get subtract(): LinearIcon { return LinearIcon.byCatalog("subtract"); }
        static get combine(): LinearIcon { return LinearIcon.byCatalog("combine"); }
        static get intersect(): LinearIcon { return LinearIcon.byCatalog("intersect"); }
        static get exclude(): LinearIcon { return LinearIcon.byCatalog("exclude"); }
        static get align_center_vertical(): LinearIcon { return LinearIcon.byCatalog("align-center-vertical"); }
        static get align_right(): LinearIcon { return LinearIcon.byCatalog("align-right"); }
        static get align_bottom(): LinearIcon { return LinearIcon.byCatalog("align-bottom"); }
        static get align_left(): LinearIcon { return LinearIcon.byCatalog("align-left"); }
        static get align_center_horizontal(): LinearIcon { return LinearIcon.byCatalog("align-center-horizontal"); }
        static get align_top(): LinearIcon { return LinearIcon.byCatalog("align-top"); }
        static get square(): LinearIcon { return LinearIcon.byCatalog("square"); }
        static get plus_square(): LinearIcon { return LinearIcon.byCatalog("plus-square"); }
        static get minus_square(): LinearIcon { return LinearIcon.byCatalog("minus-square"); }
        static get percent_square(): LinearIcon { return LinearIcon.byCatalog("percent-square"); }
        static get arrow_up_square(): LinearIcon { return LinearIcon.byCatalog("arrow-up-square"); }
        static get arrow_down_square(): LinearIcon { return LinearIcon.byCatalog("arrow-down-square"); }
        static get arrow_left_square(): LinearIcon { return LinearIcon.byCatalog("arrow-left-square"); }
        static get arrow_right_square(): LinearIcon { return LinearIcon.byCatalog("arrow-right-square"); }
        static get chevron_up_square(): LinearIcon { return LinearIcon.byCatalog("chevron-up-square"); }
        static get chevron_down_square(): LinearIcon { return LinearIcon.byCatalog("chevron-down-square"); }
        static get chevron_left_square(): LinearIcon { return LinearIcon.byCatalog("chevron-left-square"); }
        static get chevron_right_square(): LinearIcon { return LinearIcon.byCatalog("chevron-right-square"); }
        static get check_square(): LinearIcon { return LinearIcon.byCatalog("check-square"); }
        static get cross_square(): LinearIcon { return LinearIcon.byCatalog("cross-square"); }
        static get menu_square(): LinearIcon { return LinearIcon.byCatalog("menu-square"); }
        static get prohibited(): LinearIcon { return LinearIcon.byCatalog("prohibited"); }
        static get circle(): LinearIcon { return LinearIcon.byCatalog("circle"); }
        static get radio_button(): LinearIcon { return LinearIcon.byCatalog("radio-button"); }
        static get ligature(): LinearIcon { return LinearIcon.byCatalog("ligature"); }
        static get text_format(): LinearIcon { return LinearIcon.byCatalog("text-format"); }
        static get text_format_remove(): LinearIcon { return LinearIcon.byCatalog("text-format-remove"); }
        static get text_size(): LinearIcon { return LinearIcon.byCatalog("text-size"); }
        static get bold(): LinearIcon { return LinearIcon.byCatalog("bold"); }
        static get italic(): LinearIcon { return LinearIcon.byCatalog("italic"); }
        static get underline(): LinearIcon { return LinearIcon.byCatalog("underline"); }
        static get strikethrough(): LinearIcon { return LinearIcon.byCatalog("strikethrough"); }
        static get highlight(): LinearIcon { return LinearIcon.byCatalog("highlight"); }
        static get text_align_left(): LinearIcon { return LinearIcon.byCatalog("text-align-left"); }
        static get text_align_center(): LinearIcon { return LinearIcon.byCatalog("text-align-center"); }
        static get text_align_right(): LinearIcon { return LinearIcon.byCatalog("text-align-right"); }
        static get text_align_justify(): LinearIcon { return LinearIcon.byCatalog("text-align-justify"); }
        static get line_spacing(): LinearIcon { return LinearIcon.byCatalog("line-spacing"); }
        static get indent_increase(): LinearIcon { return LinearIcon.byCatalog("indent-increase"); }
        static get indent_decrease(): LinearIcon { return LinearIcon.byCatalog("indent-decrease"); }
        static get text_wrap(): LinearIcon { return LinearIcon.byCatalog("text-wrap"); }
        static get pilcrow(): LinearIcon { return LinearIcon.byCatalog("pilcrow"); }
        static get direction_ltr(): LinearIcon { return LinearIcon.byCatalog("direction-ltr"); }
        static get direction_rtl(): LinearIcon { return LinearIcon.byCatalog("direction-rtl"); }
        static get page_break(): LinearIcon { return LinearIcon.byCatalog("page-break"); }
        static get page_break2(): LinearIcon { return LinearIcon.byCatalog("page-break2"); }
        static get sort_alpha_asc(): LinearIcon { return LinearIcon.byCatalog("sort-alpha-asc"); }
        static get sort_alpha_desc(): LinearIcon { return LinearIcon.byCatalog("sort-alpha-desc"); }
        static get sort_numeric_asc(): LinearIcon { return LinearIcon.byCatalog("sort-numeric-asc"); }
        static get sort_numeric_desc(): LinearIcon { return LinearIcon.byCatalog("sort-numeric-desc"); }
        static get sort_amount_asc(): LinearIcon { return LinearIcon.byCatalog("sort-amount-asc"); }
        static get sort_amount_desc(): LinearIcon { return LinearIcon.byCatalog("sort-amount-desc"); }
        static get sort_time_asc(): LinearIcon { return LinearIcon.byCatalog("sort-time-asc"); }
        static get sort_time_desc(): LinearIcon { return LinearIcon.byCatalog("sort-time-desc"); }
        static get sigma(): LinearIcon { return LinearIcon.byCatalog("sigma"); }
        static get pencil_line(): LinearIcon { return LinearIcon.byCatalog("pencil-line"); }
        static get hand(): LinearIcon { return LinearIcon.byCatalog("hand"); }
        static get pointer_up(): LinearIcon { return LinearIcon.byCatalog("pointer-up"); }
        static get pointer_right(): LinearIcon { return LinearIcon.byCatalog("pointer-right"); }
        static get pointer_down(): LinearIcon { return LinearIcon.byCatalog("pointer-down"); }
        static get pointer_left(): LinearIcon { return LinearIcon.byCatalog("pointer-left"); }
        static get finger_tap(): LinearIcon { return LinearIcon.byCatalog("finger-tap"); }
        static get fingers_tap(): LinearIcon { return LinearIcon.byCatalog("fingers-tap"); }
        static get reminder(): LinearIcon { return LinearIcon.byCatalog("reminder"); }
        static get fingers_crossed(): LinearIcon { return LinearIcon.byCatalog("fingers-crossed"); }
        static get fingers_victory(): LinearIcon { return LinearIcon.byCatalog("fingers-victory"); }
        static get gesture_zoom(): LinearIcon { return LinearIcon.byCatalog("gesture-zoom"); }
        static get gesture_pinch(): LinearIcon { return LinearIcon.byCatalog("gesture-pinch"); }
        static get fingers_scroll_horizontal(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-horizontal"); }
        static get fingers_scroll_vertical(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-vertical"); }
        static get fingers_scroll_left(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-left"); }
        static get fingers_scroll_right(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-right"); }
        static get hand2(): LinearIcon { return LinearIcon.byCatalog("hand2"); }
        static get pointer_up2(): LinearIcon { return LinearIcon.byCatalog("pointer-up2"); }
        static get pointer_right2(): LinearIcon { return LinearIcon.byCatalog("pointer-right2"); }
        static get pointer_down2(): LinearIcon { return LinearIcon.byCatalog("pointer-down2"); }
        static get pointer_left2(): LinearIcon { return LinearIcon.byCatalog("pointer-left2"); }
        static get finger_tap2(): LinearIcon { return LinearIcon.byCatalog("finger-tap2"); }
        static get fingers_tap2(): LinearIcon { return LinearIcon.byCatalog("fingers-tap2"); }
        static get reminder2(): LinearIcon { return LinearIcon.byCatalog("reminder2"); }
        static get gesture_zoom2(): LinearIcon { return LinearIcon.byCatalog("gesture-zoom2"); }
        static get gesture_pinch2(): LinearIcon { return LinearIcon.byCatalog("gesture-pinch2"); }
        static get fingers_scroll_horizontal2(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-horizontal2"); }
        static get fingers_scroll_vertical2(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-vertical2"); }
        static get fingers_scroll_left2(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-left2"); }
        static get fingers_scroll_right2(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-right2"); }
        static get fingers_scroll_vertical3(): LinearIcon { return LinearIcon.byCatalog("fingers-scroll-vertical3"); }
        static get border_style(): LinearIcon { return LinearIcon.byCatalog("border-style"); }
        static get border_all(): LinearIcon { return LinearIcon.byCatalog("border-all"); }
        static get border_outer(): LinearIcon { return LinearIcon.byCatalog("border-outer"); }
        static get border_inner(): LinearIcon { return LinearIcon.byCatalog("border-inner"); }
        static get border_top(): LinearIcon { return LinearIcon.byCatalog("border-top"); }
        static get border_horizontal(): LinearIcon { return LinearIcon.byCatalog("border-horizontal"); }
        static get border_bottom(): LinearIcon { return LinearIcon.byCatalog("border-bottom"); }
        static get border_left(): LinearIcon { return LinearIcon.byCatalog("border-left"); }
        static get border_vertical(): LinearIcon { return LinearIcon.byCatalog("border-vertical"); }
        static get border_right(): LinearIcon { return LinearIcon.byCatalog("border-right"); }
        static get border_none(): LinearIcon { return LinearIcon.byCatalog("border-none"); }
        static get ellipsis(): LinearIcon { return LinearIcon.byCatalog("ellipsis"); }
        static get uni21(): LinearIcon { return LinearIcon.byCatalog("uni21"); }
        static get uni22(): LinearIcon { return LinearIcon.byCatalog("uni22"); }
        static get uni23(): LinearIcon { return LinearIcon.byCatalog("uni23"); }
        static get uni24(): LinearIcon { return LinearIcon.byCatalog("uni24"); }
        static get uni25(): LinearIcon { return LinearIcon.byCatalog("uni25"); }
        static get uni26(): LinearIcon { return LinearIcon.byCatalog("uni26"); }
        static get uni27(): LinearIcon { return LinearIcon.byCatalog("uni27"); }
        static get uni28(): LinearIcon { return LinearIcon.byCatalog("uni28"); }
        static get uni29(): LinearIcon { return LinearIcon.byCatalog("uni29"); }
        static get uni2a(): LinearIcon { return LinearIcon.byCatalog("uni2a"); }
        static get uni2b(): LinearIcon { return LinearIcon.byCatalog("uni2b"); }
        static get uni2c(): LinearIcon { return LinearIcon.byCatalog("uni2c"); }
        static get uni2d(): LinearIcon { return LinearIcon.byCatalog("uni2d"); }
        static get uni2e(): LinearIcon { return LinearIcon.byCatalog("uni2e"); }
        static get uni2f(): LinearIcon { return LinearIcon.byCatalog("uni2f"); }
        static get uni30(): LinearIcon { return LinearIcon.byCatalog("uni30"); }
        static get uni31(): LinearIcon { return LinearIcon.byCatalog("uni31"); }
        static get uni32(): LinearIcon { return LinearIcon.byCatalog("uni32"); }
        static get uni33(): LinearIcon { return LinearIcon.byCatalog("uni33"); }
        static get uni34(): LinearIcon { return LinearIcon.byCatalog("uni34"); }
        static get uni35(): LinearIcon { return LinearIcon.byCatalog("uni35"); }
        static get uni37(): LinearIcon { return LinearIcon.byCatalog("uni37"); }
        static get uni38(): LinearIcon { return LinearIcon.byCatalog("uni38"); }
        static get uni39(): LinearIcon { return LinearIcon.byCatalog("uni39"); }
        static get uni3a(): LinearIcon { return LinearIcon.byCatalog("uni3a"); }
        static get uni3b(): LinearIcon { return LinearIcon.byCatalog("uni3b"); }
        static get uni3c(): LinearIcon { return LinearIcon.byCatalog("uni3c"); }
        static get uni3d(): LinearIcon { return LinearIcon.byCatalog("uni3d"); }
        static get uni3e(): LinearIcon { return LinearIcon.byCatalog("uni3e"); }
        static get uni3f(): LinearIcon { return LinearIcon.byCatalog("uni3f"); }
        static get uni40(): LinearIcon { return LinearIcon.byCatalog("uni40"); }
        static get uni41(): LinearIcon { return LinearIcon.byCatalog("uni41"); }
        static get uni42(): LinearIcon { return LinearIcon.byCatalog("uni42"); }
        static get uni43(): LinearIcon { return LinearIcon.byCatalog("uni43"); }
        static get uni44(): LinearIcon { return LinearIcon.byCatalog("uni44"); }
        static get uni45(): LinearIcon { return LinearIcon.byCatalog("uni45"); }
        static get uni46(): LinearIcon { return LinearIcon.byCatalog("uni46"); }
        static get uni47(): LinearIcon { return LinearIcon.byCatalog("uni47"); }
        static get uni48(): LinearIcon { return LinearIcon.byCatalog("uni48"); }
        static get uni49(): LinearIcon { return LinearIcon.byCatalog("uni49"); }
        static get uni4a(): LinearIcon { return LinearIcon.byCatalog("uni4a"); }
        static get uni4b(): LinearIcon { return LinearIcon.byCatalog("uni4b"); }
        static get uni4c(): LinearIcon { return LinearIcon.byCatalog("uni4c"); }
        static get uni4d(): LinearIcon { return LinearIcon.byCatalog("uni4d"); }
        static get uni4e(): LinearIcon { return LinearIcon.byCatalog("uni4e"); }
        static get uni4f(): LinearIcon { return LinearIcon.byCatalog("uni4f"); }
        static get uni50(): LinearIcon { return LinearIcon.byCatalog("uni50"); }
        static get uni51(): LinearIcon { return LinearIcon.byCatalog("uni51"); }
        static get uni52(): LinearIcon { return LinearIcon.byCatalog("uni52"); }
        static get uni53(): LinearIcon { return LinearIcon.byCatalog("uni53"); }
        static get uni54(): LinearIcon { return LinearIcon.byCatalog("uni54"); }
        static get uni55(): LinearIcon { return LinearIcon.byCatalog("uni55"); }
        static get uni56(): LinearIcon { return LinearIcon.byCatalog("uni56"); }
        static get uni57(): LinearIcon { return LinearIcon.byCatalog("uni57"); }
        static get uni58(): LinearIcon { return LinearIcon.byCatalog("uni58"); }
        static get uni59(): LinearIcon { return LinearIcon.byCatalog("uni59"); }
        static get uni5a(): LinearIcon { return LinearIcon.byCatalog("uni5a"); }
        static get uni5b(): LinearIcon { return LinearIcon.byCatalog("uni5b"); }
        static get uni5c(): LinearIcon { return LinearIcon.byCatalog("uni5c"); }
        static get uni5d(): LinearIcon { return LinearIcon.byCatalog("uni5d"); }
        static get uni5e(): LinearIcon { return LinearIcon.byCatalog("uni5e"); }
        static get uni5f(): LinearIcon { return LinearIcon.byCatalog("uni5f"); }
        static get uni60(): LinearIcon { return LinearIcon.byCatalog("uni60"); }
        static get uni61(): LinearIcon { return LinearIcon.byCatalog("uni61"); }
        static get uni62(): LinearIcon { return LinearIcon.byCatalog("uni62"); }
        static get uni63(): LinearIcon { return LinearIcon.byCatalog("uni63"); }
        static get uni64(): LinearIcon { return LinearIcon.byCatalog("uni64"); }
        static get uni65(): LinearIcon { return LinearIcon.byCatalog("uni65"); }
        static get uni66(): LinearIcon { return LinearIcon.byCatalog("uni66"); }
        static get uni67(): LinearIcon { return LinearIcon.byCatalog("uni67"); }
        static get uni68(): LinearIcon { return LinearIcon.byCatalog("uni68"); }
        static get uni69(): LinearIcon { return LinearIcon.byCatalog("uni69"); }
        static get uni6a(): LinearIcon { return LinearIcon.byCatalog("uni6a"); }
        static get uni6b(): LinearIcon { return LinearIcon.byCatalog("uni6b"); }
        static get uni6c(): LinearIcon { return LinearIcon.byCatalog("uni6c"); }
        static get uni6d(): LinearIcon { return LinearIcon.byCatalog("uni6d"); }
        static get uni6e(): LinearIcon { return LinearIcon.byCatalog("uni6e"); }
        static get uni6f(): LinearIcon { return LinearIcon.byCatalog("uni6f"); }
        static get uni70(): LinearIcon { return LinearIcon.byCatalog("uni70"); }
        static get uni71(): LinearIcon { return LinearIcon.byCatalog("uni71"); }
        static get uni72(): LinearIcon { return LinearIcon.byCatalog("uni72"); }
        static get uni73(): LinearIcon { return LinearIcon.byCatalog("uni73"); }
        static get uni74(): LinearIcon { return LinearIcon.byCatalog("uni74"); }
        static get uni75(): LinearIcon { return LinearIcon.byCatalog("uni75"); }
        static get uni76(): LinearIcon { return LinearIcon.byCatalog("uni76"); }
        static get uni77(): LinearIcon { return LinearIcon.byCatalog("uni77"); }
        static get uni78(): LinearIcon { return LinearIcon.byCatalog("uni78"); }
        static get uni79(): LinearIcon { return LinearIcon.byCatalog("uni79"); }
        static get uni7a(): LinearIcon { return LinearIcon.byCatalog("uni7a"); }
        static get uni7b(): LinearIcon { return LinearIcon.byCatalog("uni7b"); }
        static get uni7c(): LinearIcon { return LinearIcon.byCatalog("uni7c"); }
        static get uni7d(): LinearIcon { return LinearIcon.byCatalog("uni7d"); }
        static get uni7e(): LinearIcon { return LinearIcon.byCatalog("uni7e"); }
        static get copyright(): LinearIcon { return LinearIcon.byCatalog("copyright"); }
        //endregion

    }

}